import type { SeedPrompt } from './prompt-data';

export const SEED_PROMPTS_BATCH_2: SeedPrompt[] = [
  {
    slug: 'claude-research-assistant',
    title: 'Claude Research Assistant',
    description: 'Deep research and analysis prompt for Claude with structured output and citation tracking.',
    content: 'You are a research assistant. I need a comprehensive analysis of: [TOPIC]. Research depth: [BRIEF/MODERATE/DEEP]. Provide:\n1. Executive summary (200 words)\n2. Key findings with supporting evidence\n3. Contradictory viewpoints and debates\n4. Historical context and timeline\n5. Current state and recent developments\n6. Future predictions and trends\n7. Key stakeholders and their positions\n8. Recommended further reading\n\nFormat with clear headings. Be objective and cite sources where possible.',
    category: 'claude',
    ai_models: ['claude', 'chatgpt'],
    difficulty: 'Intermediate',
    tags: ['research', 'analysis', 'claude', 'deep-dive'],
    author_name: 'ResearchRaven',
    author_avatar: '🦉',
    featured: true,
    trending: true,
    copies_count: 7800,
    likes_count: 2300,
    rating_avg: 4.9,
    rating_count: 560,
    expected_output: 'A structured research report with findings, analysis, and citations.',
    tips: 'Claude excels at nuanced analysis. Ask follow-up questions to go deeper on specific points.',
  },
  {
    slug: 'gemini-data-analyst',
    title: 'Gemini Data Analyst',
    description: 'Analyze datasets with Gemini for patterns, insights, and visual recommendations.',
    content: 'You are a data analyst. Analyze the following dataset:\n[PASTE DATA OR DESCRIBE DATASET]\n\nProvide:\n1. Data quality assessment (missing values, outliers, inconsistencies)\n2. Statistical summary (mean, median, std dev, correlations)\n3. Key patterns and trends\n4. Anomalies and outliers with explanations\n5. Predictive insights\n6. Recommended visualizations (chart type, variables, purpose)\n7. Business recommendations based on the data\n8. Questions the data raises that need further investigation',
    category: 'gemini',
    ai_models: ['gemini', 'chatgpt', 'claude'],
    difficulty: 'Advanced',
    tags: ['data-analysis', 'gemini', 'analytics', 'insights'],
    author_name: 'DataDynamo',
    author_avatar: '📊',
    featured: false,
    trending: true,
    copies_count: 5600,
    likes_count: 1700,
    rating_avg: 4.7,
    rating_count: 390,
    expected_output: 'A comprehensive data analysis report with statistical insights and visualization recommendations.',
    tips: 'Gemini integrates with Google Sheets. Use it for real-time data analysis workflows.',
  },
  {
    slug: 'stable-diffusion-landscape',
    title: 'Epic Landscape Generator',
    description: 'Create breathtaking landscape image prompts for Stable Diffusion with artistic control.',
    content: 'Generate an epic landscape image prompt for Stable Diffusion. Landscape type: [MOUNTAINS/OCEAN/FOREST/DESERT/SPACE]. Time of day: [DAWN/DUSK/NIGHT/MIDNIGHT]. Weather: [CLEAR/STORMY/FOGGY/SNOWY]. Art style: [PHOTOREALISTIC/PAINTERLY/FANTASY/SCIFI]. Mood: [SERENE/EPIC/MYSTICAL/FOREBODING]. Key elements: [LIST ELEMENTS]. Camera: wide angle, deep depth of field. Quality tags: masterpiece, best quality, highly detailed, 8K, HDR, dramatic lighting. Negative prompt: blurry, low quality, distorted, watermark, text.',
    category: 'stable-diffusion',
    ai_models: ['stable-diffusion', 'flux', 'midjourney'],
    difficulty: 'Intermediate',
    tags: ['stable-diffusion', 'landscape', 'art', 'image-generation'],
    author_name: 'LandscapeLord',
    author_avatar: '🏔️',
    featured: false,
    trending: false,
    copies_count: 4100,
    likes_count: 1300,
    rating_avg: 4.5,
    rating_count: 290,
    expected_output: 'A detailed Stable Diffusion prompt with positive and negative prompts for epic landscapes.',
    tips: 'Add "negative prompt" keywords to avoid common AI art artifacts.',
  },
  {
    slug: 'sora-video-concept',
    title: 'Sora Video Concept Board',
    description: 'Design detailed video concepts for Sora with scene descriptions, camera moves, and visual style.',
    content: 'Create a detailed video concept for Sora AI video generation. Concept: [VIDEO IDEA]. Duration: [SECONDS]. Visual style: [CINEMATIC/DOCUMENTARY/ANIMATED/ABSTRACT]. Camera style: [STATIC/HANDHELD/DRONE/DOLLY]. Provide:\n1. Scene-by-scene breakdown (each scene 3-5 seconds)\n2. Camera movement description for each scene\n3. Lighting and color grading notes\n4. Subject action description\n5. Background and environment details\n6. Audio/mood description\n7. Transition style between scenes\n8. Full combined prompt for Sora',
    category: 'sora',
    ai_models: ['sora', 'veo'],
    difficulty: 'Advanced',
    tags: ['sora', 'video-generation', 'ai-video', 'storyboard'],
    author_name: 'VideoVisionary',
    author_avatar: '🎥',
    featured: false,
    trending: true,
    copies_count: 3200,
    likes_count: 1100,
    rating_avg: 4.6,
    rating_count: 210,
    expected_output: 'A structured video concept with scene breakdowns and a combined Sora prompt.',
    tips: 'Keep scenes under 5 seconds each for best results with AI video generation.',
  },
  {
    slug: 'veo-product-demo',
    title: 'Veo Product Demo Script',
    description: 'Create AI-generated product demo video concepts optimized for Google Veo.',
    content: 'Create a product demo video concept for Veo. Product: [PRODUCT NAME]. Key features to highlight: [LIST]. Target audience: [AUDIENCE]. Video length: [DURATION]. Provide:\n1. Opening shot description (product reveal)\n2. Feature showcase scenes (one per feature)\n3. Use case scenarios (2-3 real-world applications)\n4. Closing shot with brand logo\n5. Camera angles and movements for each scene\n6. Lighting setup recommendations\n7. Text overlay suggestions\n8. Background music mood\n9. Full Veo-optimized prompt',
    category: 'veo',
    ai_models: ['veo', 'sora'],
    difficulty: 'Intermediate',
    tags: ['veo', 'product-demo', 'video', 'marketing'],
    author_name: 'DemoDirector',
    author_avatar: '🎬',
    featured: false,
    trending: false,
    copies_count: 1800,
    likes_count: 700,
    rating_avg: 4.4,
    rating_count: 120,
    expected_output: 'A product demo video concept with scene descriptions and a Veo-optimized prompt.',
    tips: 'Focus on one key feature per scene. Too many features in one shot dilutes the message.',
  },
  {
    slug: 'zapier-automation-blueprint',
    title: 'Zapier Automation Blueprint',
    description: 'Design complete Zapier automation flows with trigger apps, actions, and optimization tips.',
    content: 'Design a Zapier automation for: [WORKFLOW GOAL]. Trigger app: [APP NAME]. Trigger event: [EVENT]. Actions needed: [LIST DESIRED ACTIONS]. Apps available: [LIST YOUR CONNECTED APPS]. Provide:\n1. Step-by-step Zap configuration (trigger + each action)\n2. Data mapping between steps\n3. Filter conditions if needed\n4. Error handling and retry strategy\n5. Testing checklist\n6. Optimization tips (rate limits, task usage)\n7. Alternative approaches\n8. Cost estimate based on Zapier plan',
    category: 'zapier',
    ai_models: ['chatgpt', 'claude'],
    difficulty: 'Intermediate',
    tags: ['zapier', 'automation', 'workflow', 'integration'],
    author_name: 'ZapMaster',
    author_avatar: '⚡',
    featured: false,
    trending: false,
    copies_count: 2400,
    likes_count: 900,
    rating_avg: 4.5,
    rating_count: 200,
    expected_output: 'A complete Zapier automation blueprint with step configurations and testing checklist.',
    tips: 'Use Zapier Filters to prevent unnecessary task consumption on your plan.',
  },
  {
    slug: 'excel-formula-generator',
    title: 'Excel Formula Generator',
    description: 'Generate complex Excel formulas from plain English descriptions. VLOOKUP, INDEX/MATCH, pivot tables and more.',
    content: 'You are an Excel expert. I need a formula for: [DESCRIBE WHAT YOU WANT TO DO]. My data is in: [DESCRIBE DATA LAYOUT - sheet names, column ranges]. Excel version: [VERSION]. Provide:\n1. The exact formula (ready to copy-paste)\n2. Explanation of how it works\n3. Alternative formulas if applicable\n4. Common errors and how to fix them\n5. How to make it dynamic (drag-fill compatible)\n6. Performance notes for large datasets\n7. If VBA is needed, provide the macro code',
    category: 'excel',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['excel', 'formulas', 'spreadsheet', 'productivity'],
    author_name: 'SheetSage',
    author_avatar: '📈',
    featured: false,
    trending: true,
    copies_count: 12500,
    likes_count: 3400,
    rating_avg: 4.8,
    rating_count: 820,
    expected_output: 'A ready-to-use Excel formula with explanation and troubleshooting guide.',
    tips: 'Describe your data layout precisely (column letters, row numbers) for accurate formulas.',
  },
  {
    slug: 'twitter-thread-magnet',
    title: 'Viral Twitter Thread Builder',
    description: 'Create engaging Twitter/X threads that drive replies, retweets, and follows.',
    content: 'Write a viral Twitter/X thread about: [TOPIC]. Thread length: [NUMBER OF TWEETS]. Tone: [TONE]. Target audience: [AUDIENCE]. Key message: [MAIN POINT]. Structure:\n1. Hook tweet (must be scroll-stopping, under 280 chars)\n2. Context tweet (why this matters)\n3. Main content tweets (one idea per tweet)\n4. Evidence/data tweets (stats, examples)\n5. Contrarian or hot take tweet (optional)\n6. Summary tweet\n7. CTA tweet (follow for more, RT to share)\n\nFor each tweet, provide the exact text and suggest an image/GIF type.',
    category: 'social-media',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['twitter', 'thread', 'social-media', 'content'],
    author_name: 'ThreadKing',
    author_avatar: '🐦',
    featured: false,
    trending: true,
    copies_count: 9800,
    likes_count: 2800,
    rating_avg: 4.6,
    rating_count: 590,
    expected_output: 'A complete Twitter thread with tweet-by-tweet breakdown and visual suggestions.',
    tips: 'The hook tweet gets 80% of the thread\'s success. Spend most of your time on it.',
  },
  {
    slug: 'linkedin-thought-leader',
    title: 'LinkedIn Thought Leadership Post',
    description: 'Write LinkedIn posts that build authority, spark discussion, and grow your professional network.',
    content: 'Write a LinkedIn post for: [YOUR ROLE/TOPIC]. Goal: [BUILD AUTHORITY / DRIVE DISCUSSION / ANNOUNCE NEWS]. Tone: [PROFESSIONAL/CASUAL/INSPIRATIONAL]. Key insight: [YOUR MAIN POINT]. Personal story element: [BRIEF STORY]. Provide:\n1. Hook line (first 2 lines must create curiosity before the "see more")\n2. Main body (3-5 short paragraphs, max 1 sentence each)\n3. Key takeaway or lesson\n4. Discussion question to drive comments\n5. 5 relevant hashtags\n6. Best posting time for your audience\n7. Comment response templates (for the first 10 comments)',
    category: 'social-media',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['linkedin', 'thought-leadership', 'professional', 'networking'],
    author_name: 'LinkedInLeader',
    author_avatar: '💼',
    featured: false,
    trending: false,
    copies_count: 8200,
    likes_count: 2400,
    rating_avg: 4.5,
    rating_count: 520,
    expected_output: 'A LinkedIn post with hook, body, CTA, and engagement strategy.',
    tips: 'Post in the morning (7-9 AM) on weekdays for maximum reach.',
  },
  {
    slug: 'newsletter-growth-engine',
    title: 'Newsletter Growth Engine',
    description: 'Complete newsletter strategy including content, growth tactics, monetization, and retention.',
    content: 'Create a newsletter strategy for: [NEWSLETTER TOPIC]. Target subscribers: [NUMBER]. Current subscribers: [NUMBER]. Publishing frequency: [WEEKLY/BIWEEKLY/MONTHLY]. Monetization goal: [SPONSORSHIPS/PAID/PREMIUM/NONE]. Provide:\n1. Newsletter positioning and unique value proposition\n2. Name suggestions (10 options)\n3. Content pillars (3-5 recurring themes)\n4. 4-week editorial calendar\n5. Growth tactics (15 specific actions)\n6. Welcome sequence (5 emails with subject lines)\n7. Subject line formulas that work\n8. Retention strategies\n9. Monetization roadmap\n10. Key metrics to track',
    category: 'email',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Advanced',
    tags: ['newsletter', 'email', 'growth', 'content-strategy'],
    author_name: 'NewsletterNinja',
    author_avatar: '📨',
    featured: false,
    trending: false,
    copies_count: 4500,
    likes_count: 1500,
    rating_avg: 4.7,
    rating_count: 340,
    expected_output: 'A complete newsletter strategy with editorial calendar, growth tactics, and monetization plan.',
    tips: 'Focus on one content pillar per issue. Depth beats breadth for subscriber retention.',
  },
  {
    slug: 'photography-composition-coach',
    title: 'Photography Composition Coach',
    description: 'Analyze and improve your photography composition with AI-guided feedback and suggestions.',
    content: 'You are a professional photography coach. I will describe a photo I took: [DESCRIBE THE PHOTO - subject, setting, lighting, camera settings]. Analyze:\n1. Composition (rule of thirds, leading lines, framing, balance)\n2. Lighting quality and direction\n3. Color theory and harmony\n4. Depth and layering\n5. Subject placement and focus\n6. What works well\n7. Specific improvement suggestions (3-5)\n8. Recommended shooting settings for a better version\n9. Photographers or styles to study for inspiration',
    category: 'photography',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['photography', 'composition', 'feedback', 'improvement'],
    author_name: 'PhotoPro',
    author_avatar: '📸',
    featured: false,
    trending: false,
    copies_count: 3100,
    likes_count: 1000,
    rating_avg: 4.6,
    rating_count: 230,
    expected_output: 'A detailed photography critique with composition analysis and improvement suggestions.',
    tips: 'Describe your photo in detail including lighting direction and camera settings for best analysis.',
  },
  {
    slug: 'career-transition-planner',
    title: 'Career Transition Planner',
    description: 'Plan a successful career change with skills mapping, timeline, and step-by-step action plan.',
    content: 'I want to transition from [CURRENT CAREER] to [TARGET CAREER]. Current skills: [LIST]. Years of experience: [YEARS]. Available time for transition: [MONTHS]. Financial runway: [MONTHS OF SAVINGS]. Provide:\n1. Transferable skills assessment (what carries over)\n2. Skills gap analysis (what you need to learn)\n3. Learning roadmap with specific courses/certifications\n4. Portfolio/project recommendations\n5. Networking strategy (who to connect with, where)\n6. Resume and LinkedIn positioning strategy\n7. 6-month transition timeline with milestones\n8. Income bridge strategy (freelance, part-time)\n9. Common pitfalls and how to avoid them\n10. Success metrics and checkpoints',
    category: 'career',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['career', 'transition', 'planning', 'career-change'],
    author_name: 'Pathfinder',
    author_avatar: '🧭',
    featured: false,
    trending: true,
    copies_count: 6700,
    likes_count: 2000,
    rating_avg: 4.8,
    rating_count: 480,
    expected_output: 'A structured career transition plan with skills mapping, timeline, and action steps.',
    tips: 'Be realistic about your financial runway. Most career transitions take 6-12 months.',
  },
  {
    slug: 'chatgpt-roleplay-master',
    title: 'ChatGPT Roleplay Master',
    description: 'Advanced roleplay system prompt for ChatGPT with character consistency and immersive interactions.',
    content: 'You are now [CHARACTER NAME], a [CHARACTER DESCRIPTION]. Your personality: [PERSONALITY TRAITS]. Your background: [BACKSTORY]. Your speaking style: [SPEAKING STYLE]. Your knowledge: [WHAT YOU KNOW AND DON\'T KNOW]. Your opinions: [KEY OPINIONS AND BELIEFS]. Rules:\n1. Never break character\n2. Never mention you are an AI\n3. Stay consistent with your background\n4. React emotionally as the character would\n5. Use your character\'s vocabulary and speech patterns\n6. If asked something outside your knowledge, respond as the character would (confusion, curiosity, etc.)\n\nBegin by introducing yourself in character.',
    category: 'chatgpt',
    ai_models: ['chatgpt', 'claude'],
    difficulty: 'Intermediate',
    tags: ['roleplay', 'character', 'chatgpt', 'creative'],
    author_name: 'RoleMaster',
    author_avatar: '🎭',
    featured: false,
    trending: false,
    copies_count: 5400,
    likes_count: 1700,
    rating_avg: 4.5,
    rating_count: 410,
    expected_output: 'An immersive character roleplay setup with consistent personality and speech patterns.',
    tips: 'The more detailed the character description, the more consistent the roleplay will be.',
  },
  {
    slug: 'business-swot-analyzer',
    title: 'Business SWOT Analyzer',
    description: 'Generate a detailed SWOT analysis for any business with strategic recommendations.',
    content: 'Create a comprehensive SWOT analysis for: [BUSINESS NAME/TYPE]. Industry: [INDUSTRY]. Stage: [STARTUP/GROWTH/MATURE]. Key competitors: [LIST]. Provide:\n1. Strengths (5-7 items with explanations)\n2. Weaknesses (5-7 items with explanations)\n3. Opportunities (5-7 items with explanations)\n4. Threats (5-7 items with explanations)\n5. SWOT matrix summary\n6. Strategic recommendations based on the analysis (TOWS matrix)\n7. Priority actions (top 5)\n8. Risk mitigation strategies\n9. Competitive advantage assessment\n10. 90-day action plan',
    category: 'business',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['swot', 'business-strategy', 'analysis', 'planning'],
    author_name: 'StrategySage',
    author_avatar: '📋',
    featured: false,
    trending: false,
    copies_count: 5200,
    likes_count: 1600,
    rating_avg: 4.6,
    rating_count: 380,
    expected_output: 'A detailed SWOT analysis with TOWS matrix and 90-day action plan.',
    tips: 'Be honest about weaknesses. Acknowledging them is the first step to fixing them.',
  },
  {
    slug: 'coding-architecture-reviewer',
    title: 'Software Architecture Reviewer',
    description: 'Review software architecture decisions, identify trade-offs, and recommend improvements.',
    content: 'You are a software architect. Review the following architecture for a [SYSTEM TYPE] system:\n\nArchitecture description: [DESCRIBE ARCHITECTURE - components, data flow, tech stack]\nScale requirements: [USERS/REQUESTS PER SECOND]\nKey constraints: [LIST CONSTRAINTS]\n\nAnalyze:\n1. Architecture pattern assessment (monolith, microservices, event-driven, etc.)\n2. Scalability evaluation\n3. Reliability and fault tolerance\n4. Data consistency approach\n5. Security considerations\n6. Performance bottlenecks\n7. Cost implications\n8. Trade-offs made and alternatives\n9. Recommended improvements (prioritized)\n10. Technology stack validation',
    category: 'coding',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Advanced',
    tags: ['architecture', 'system-design', 'review', 'scalability'],
    author_name: 'ArchitectAI',
    author_avatar: '🏗️',
    featured: false,
    trending: false,
    copies_count: 3800,
    likes_count: 1300,
    rating_avg: 4.7,
    rating_count: 290,
    expected_output: 'A comprehensive architecture review with trade-off analysis and improvement recommendations.',
    tips: 'Include your scale requirements for the most relevant recommendations.',
  },
  {
    slug: 'writing-story-structure',
    title: 'Story Structure Architect',
    description: 'Build compelling story structures for novels, scripts, and short stories with proven frameworks.',
    content: 'Create a story structure for: [STORY CONCEPT]. Genre: [GENRE]. Format: [NOVEL/SHORT STORY/SCREENPLAY/WEB SERIES]. Target length: [WORD COUNT/PAGES]. Provide:\n1. Logline (one-sentence summary)\n2. Three-act structure breakdown with key plot points\n3. Hero\'s Journey mapping (12 stages)\n4. Character arcs for main characters (3-5)\n5. Key scenes list (10-15 scenes with descriptions)\n6. Thematic questions and messages\n7. Subplot recommendations\n8. Pacing analysis (tension curve description)\n9. World-building checklist\n10. Opening and closing scene concepts',
    category: 'writing',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Advanced',
    tags: ['storytelling', 'structure', 'creative-writing', 'screenwriting'],
    author_name: 'StoryArchitect',
    author_avatar: '📖',
    featured: false,
    trending: false,
    copies_count: 4600,
    likes_count: 1500,
    rating_avg: 4.7,
    rating_count: 340,
    expected_output: 'A complete story structure with plot points, character arcs, and scene breakdown.',
    tips: 'Start with the logline. If you can\'t summarize your story in one sentence, the structure needs work.',
  },
  {
    slug: 'seo-content-brief',
    title: 'SEO Content Brief Generator',
    description: 'Create detailed content briefs that help writers produce SEO-optimized articles that rank.',
    content: 'Create an SEO content brief for the keyword: [TARGET KEYWORD]. Search intent: [INFORMATIONAL/COMMERCIAL/TRANSACTIONAL]. Target word count: [WORDS]. Provide:\n1. Title tag (under 60 characters, optimized)\n2. Meta description (under 160 characters)\n3. H1 heading\n4. Article outline with H2 and H3 headings\n5. Key points to cover under each heading\n6. Related keywords and LSI terms to include\n7. Questions to answer (from People Also Ask)\n8. Internal linking suggestions\n9. External linking recommendations (authoritative sources)\n10. Image/visual suggestions with alt text\n11. Featured snippet optimization strategy\n12. Call-to-action recommendation',
    category: 'seo',
    ai_models: ['chatgpt', 'claude', 'gemini', 'perplexity'],
    difficulty: 'Intermediate',
    tags: ['seo', 'content-brief', 'optimization', 'content-strategy'],
    author_name: 'ContentStrategist',
    author_avatar: '📝',
    featured: true,
    trending: false,
    copies_count: 7200,
    likes_count: 2100,
    rating_avg: 4.8,
    rating_count: 510,
    expected_output: 'A detailed SEO content brief with outline, keywords, and optimization instructions.',
    tips: 'Use Perplexity to get real-time "People Also Ask" questions for your target keyword.',
  },
  {
    slug: 'midjourney-logo-designer',
    title: 'Midjourney Logo Designer',
    description: 'Generate professional logo design prompts for Midjourney across multiple styles and industries.',
    content: 'Create a logo design prompt for Midjourney. Brand name: [BRAND NAME]. Industry: [INDUSTRY]. Logo style: [MINIMALIST/GEOMETRIC/MASCOT/LETTERMARK/EMBLEM/ABSTRACT]. Color preference: [COLORS]. Mood: [MOOD]. Provide 5 prompt variations:\n1. Minimalist version\n2. Geometric version\n3. Abstract version\n4. Vintage/retro version\n5. Modern tech version\n\nEach prompt should include: style descriptors, color palette, background (white), and parameters (--ar 1:1 --style raw --v 6). Also suggest which fonts pair well with each style.',
    category: 'midjourney',
    ai_models: ['midjourney', 'flux', 'dall-e'],
    difficulty: 'Intermediate',
    tags: ['logo', 'branding', 'midjourney', 'design'],
    author_name: 'LogoLegend',
    author_avatar: '🎯',
    featured: false,
    trending: true,
    copies_count: 6300,
    likes_count: 1900,
    rating_avg: 4.6,
    rating_count: 440,
    expected_output: 'Five Midjourney logo prompts in different styles with font pairing recommendations.',
    tips: 'Use --no text in your prompt to avoid garbled text in AI-generated logos.',
  },
  {
    slug: 'sales-objection-handler',
    title: 'Sales Objection Handler',
    description: 'Generate proven responses to any sales objection. Turn "no" into "yes" with psychology-backed frameworks.',
    content: 'You are a sales expert. I received this objection from a prospect: "[OBJECTION]". Product: [PRODUCT]. Prospect type: [BUYER PERSONA]. Price: [PRICE]. Provide:\n1. Analysis of the real concern behind the objection (price, trust, timing, fit, authority)\n2. 3 response frameworks (feel/felt/found, question, reframe)\n3. Exact scripts for each framework\n4. Follow-up questions to ask after responding\n5. Social proof or evidence to cite\n6. When to disqualify vs. persist\n7. Next steps to move the deal forward\n8. Email follow-up template if the objection is over email',
    category: 'sales',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['sales', 'objections', 'negotiation', 'closing'],
    author_name: 'CloserKing',
    author_avatar: '🤝',
    featured: false,
    trending: true,
    copies_count: 5800,
    likes_count: 1800,
    rating_avg: 4.7,
    rating_count: 430,
    expected_output: 'A structured objection handling guide with multiple response frameworks and scripts.',
    tips: 'Always acknowledge the objection before responding. People need to feel heard before they listen.',
  },
  {
    slug: 'automation-test-suite',
    title: 'Test Suite Generator',
    description: 'Generate comprehensive test suites for any code. Unit tests, integration tests, and edge cases.',
    content: 'You are a test engineer. Generate comprehensive tests for the following code:\n```\n[PASTE YOUR CODE]\n```\nLanguage: [LANGUAGE]. Testing framework: [JEST/PYTEST/JUNIT/etc.]. Provide:\n1. Unit tests for each function/method (happy path + edge cases)\n2. Integration tests for component interactions\n3. Error/exception handling tests\n4. Boundary value tests\n5. Mock/stub setup if needed\n6. Test data fixtures\n7. Coverage gaps analysis\n8. Performance/benchmark tests if applicable\n\nWrite production-ready test code with clear descriptions for each test case.',
    category: 'programming',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['testing', 'unit-tests', 'quality', 'programming'],
    author_name: 'TestTitan',
    author_avatar: '🧪',
    featured: false,
    trending: false,
    copies_count: 4900,
    likes_count: 1500,
    rating_avg: 4.6,
    rating_count: 350,
    expected_output: 'A complete test suite with unit, integration, and edge case tests ready to run.',
    tips: 'Specify your testing framework for ready-to-run code. Otherwise, the AI will guess.',
  },
  {
    slug: 'video-editing-shot-list',
    title: 'Video Shot List Generator',
    description: 'Create professional shot lists for video production with camera angles, movements, and equipment.',
    content: 'Create a professional shot list for a [VIDEO TYPE - e.g., product demo, music video, documentary, short film]. Concept: [BRIEF DESCRIPTION]. Location: [LOCATION]. Duration: [LENGTH]. Provide:\n1. Scene-by-scene shot list with:\n   - Shot number\n   - Shot type (wide, medium, close-up, extreme close-up)\n   - Camera angle (eye level, high, low, dutch)\n   - Camera movement (static, pan, tilt, dolly, handheld)\n   - Lens recommendation\n   - Lighting setup\n   - Duration\n   - Audio notes\n2. Equipment checklist\n3. B-roll suggestions\n4. Transition plan between scenes\n5. Estimated total shoot time\n6. Shot priority (must-have vs. nice-to-have)',
    category: 'video',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['video', 'shot-list', 'production', 'filmmaking'],
    author_name: 'ShotShaper',
    author_avatar: '🎥',
    featured: false,
    trending: false,
    copies_count: 2600,
    likes_count: 900,
    rating_avg: 4.5,
    rating_count: 190,
    expected_output: 'A professional shot list with camera details, equipment checklist, and production timeline.',
    tips: 'Prioritize must-have shots first. Weather and time constraints often cut nice-to-haves.',
  },
];
