import type { PromptRow } from './supabase';

export interface SeedPrompt {
  slug: string;
  title: string;
  description: string;
  content: string;
  category: string;
  ai_models: string[];
  difficulty: string;
  tags: string[];
  author_name: string;
  author_avatar: string;
  featured: boolean;
  trending: boolean;
  copies_count: number;
  likes_count: number;
  rating_avg: number;
  rating_count: number;
  expected_output: string;
  tips: string;
}

export const SEED_PROMPTS: SeedPrompt[] = [
  {
    slug: 'ultimate-code-reviewer',
    title: 'Ultimate Code Reviewer',
    description: 'A comprehensive code review prompt that analyzes code for bugs, performance, security, and best practices.',
    content: 'You are a senior software engineer performing a thorough code review. Analyze the following code for:\n1. Bugs and potential errors\n2. Performance issues\n3. Security vulnerabilities\n4. Code style and best practices\n5. Maintainability concerns\n\nFor each issue found, provide:\n- Severity (Critical/Warning/Suggestion)\n- Line number or location\n- Description of the issue\n- Suggested fix with code example\n\nCode to review:\n```\n[PASTE YOUR CODE HERE]\n```',
    category: 'coding',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['code-review', 'debugging', 'best-practices', 'security'],
    author_name: 'DevMaster',
    author_avatar: '👨‍💻',
    featured: true,
    trending: true,
    copies_count: 12450,
    likes_count: 3420,
    rating_avg: 4.9,
    rating_count: 856,
    expected_output: 'A structured code review report with categorized issues, severity ratings, and code fix suggestions.',
    tips: 'Paste your entire file or function for best results. Works with any programming language.',
  },
  {
    slug: 'blog-post-writer-pro',
    title: 'Blog Post Writer Pro',
    description: 'Generate a complete, SEO-optimized blog post with introduction, body paragraphs, and conclusion.',
    content: 'Write a comprehensive blog post about [TOPIC]. Requirements:\n- Target audience: [AUDIENCE]\n- Tone: [TONE]\n- Word count: 1500-2000 words\n- Include an engaging introduction with a hook\n- Use H2 and H3 headings for structure\n- Include actionable tips and examples\n- Add a FAQ section at the end\n- Optimize for the keyword: [KEYWORD]\n- Include a call-to-action at the end\n\nMake it engaging, informative, and easy to read.',
    category: 'writing',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['blog', 'content', 'seo', 'writing'],
    author_name: 'ContentQueen',
    author_avatar: '✍️',
    featured: true,
    trending: true,
    copies_count: 18900,
    likes_count: 5230,
    rating_avg: 4.8,
    rating_count: 1200,
    expected_output: 'A complete, well-structured blog post ready to publish with SEO optimization.',
    tips: 'Replace [TOPIC], [AUDIENCE], [TONE], and [KEYWORD] with your specific details.',
  },
  {
    slug: 'midjourney-cinematic-portrait',
    title: 'Cinematic Portrait Master',
    description: 'Generate stunning cinematic portrait prompts for Midjourney with professional lighting and composition.',
    content: 'Create a cinematic portrait of [SUBJECT]. Style: cinematic film photography, shot on Arri Alexa, anamorphic lens, shallow depth of field. Lighting: [LIGHTING STYLE - e.g., rim lighting, golden hour, moody shadows]. Composition: rule of thirds, subject looking [DIRECTION]. Color grading: [COLOR PALETTE - e.g., teal and orange, desaturated, warm]. Mood: [MOOD - e.g., mysterious, hopeful, dramatic]. Background: [BACKGROUND DESCRIPTION]. --ar 2:3 --style raw --v 6',
    category: 'midjourney',
    ai_models: ['midjourney', 'stable-diffusion', 'flux'],
    difficulty: 'Intermediate',
    tags: ['portrait', 'cinematic', 'photography', 'midjourney'],
    author_name: 'VisualArtist',
    author_avatar: '🎨',
    featured: true,
    trending: true,
    copies_count: 9800,
    likes_count: 2800,
    rating_avg: 4.9,
    rating_count: 640,
    expected_output: 'A detailed Midjourney prompt that generates a professional cinematic portrait.',
    tips: 'Experiment with different lighting styles and color palettes for unique results.',
  },
  {
    slug: 'email-cold-outreach',
    title: 'Cold Email That Gets Replies',
    description: 'Write cold outreach emails that get opened, read, and replied to. Proven framework for B2B sales.',
    content: 'Write a cold outreach email to [PROSPECT NAME] at [COMPANY]. Context: I am reaching out because [REASON]. My product/service: [WHAT YOU OFFER]. The value for them: [SPECIFIC VALUE PROPOSITION]. Keep it under 150 words. Use a conversational tone. Include a clear, low-friction call-to-action. Subject line should be under 5 words and create curiosity. Do NOT use generic openers like "I hope this finds you well."',
    category: 'email',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['cold-email', 'sales', 'outreach', 'b2b'],
    author_name: 'SalesPro',
    author_avatar: '📧',
    featured: false,
    trending: true,
    copies_count: 15600,
    likes_count: 4100,
    rating_avg: 4.7,
    rating_count: 980,
    expected_output: 'A concise, compelling cold email with subject line that avoids spam filters.',
    tips: 'Personalize the [REASON] field with something specific about the prospect for better reply rates.',
  },
  {
    slug: 'seo-keyword-research',
    title: 'SEO Keyword Research Master',
    description: 'Comprehensive keyword research prompt that finds high-volume, low-competition keywords for any niche.',
    content: 'Act as an SEO expert. Perform comprehensive keyword research for the niche: [NICHE]. Provide:\n1. 20 primary keywords with estimated monthly search volume and competition level\n2. 10 long-tail keywords (4+ words) with high conversion potential\n3. 5 question-based keywords for FAQ content\n4. 5 commercial intent keywords for product/service pages\n5. Top 3 keyword clusters for content silo strategy\n\nFor each keyword, explain why it is valuable and suggest a content format (blog post, landing page, video, etc.).',
    category: 'seo',
    ai_models: ['chatgpt', 'claude', 'gemini', 'perplexity'],
    difficulty: 'Intermediate',
    tags: ['seo', 'keywords', 'research', 'content-strategy'],
    author_name: 'SEOGuru',
    author_avatar: '🔍',
    featured: true,
    trending: false,
    copies_count: 8200,
    likes_count: 2100,
    rating_avg: 4.6,
    rating_count: 520,
    expected_output: 'A structured keyword research report with categorized keywords and content recommendations.',
    tips: 'Use Perplexity for real-time search volume data.',
  },
  {
    slug: 'instagram-viral-reel',
    title: 'Viral Instagram Reel Script',
    description: 'Create scroll-stopping Instagram Reel scripts with hooks, pacing, and CTAs designed for virality.',
    content: 'Create a 30-second Instagram Reel script for [NICHE/TOPIC]. Structure:\n- Hook (first 3 seconds): Must stop the scroll. Use curiosity, shock, or relatability.\n- Body (15-20 seconds): Deliver value quickly. Use fast cuts and text overlays.\n- CTA (last 5 seconds): Drive engagement (save, share, follow).\n\nInclude:\n- Exact spoken script word-by-word\n- Text overlay suggestions for each scene\n- Music mood recommendation\n- Hashtag suggestions (10 relevant tags)\n- Best posting time for this content type',
    category: 'social-media',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['instagram', 'reels', 'video', 'viral', 'social-media'],
    author_name: 'ReelMaster',
    author_avatar: '📱',
    featured: false,
    trending: true,
    copies_count: 11200,
    likes_count: 3200,
    rating_avg: 4.5,
    rating_count: 710,
    expected_output: 'A complete Reel script with scene-by-scene breakdown, text overlays, and posting strategy.',
    tips: 'The first 3 seconds are critical. Test multiple hooks to find what works for your audience.',
  },
  {
    slug: 'startup-pitch-deck',
    title: 'Startup Pitch Deck Generator',
    description: 'Generate a complete pitch deck narrative for investor presentations. Problem, solution, market, traction, and ask.',
    content: 'Create a compelling pitch deck narrative for a startup. Company: [COMPANY NAME]. Industry: [INDUSTRY]. Product: [BRIEF DESCRIPTION]. Target market: [TARGET MARKET]. Current traction: [METRICS OR STAGE]. Funding ask: [AMOUNT]. Use the standard 10-slide structure:\n1. Title slide\n2. Problem\n3. Solution\n4. Market size (TAM/SAM/SOM)\n5. Product/Demo\n6. Business model\n7. Go-to-market strategy\n8. Competition and differentiation\n9. Team\n10. Financial projections and the ask\n\nFor each slide, provide the key talking points and suggested visual elements.',
    category: 'business',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Advanced',
    tags: ['startup', 'pitch-deck', 'investors', 'fundraising'],
    author_name: 'VenturePro',
    author_avatar: '🚀',
    featured: true,
    trending: false,
    copies_count: 6400,
    likes_count: 1800,
    rating_avg: 4.8,
    rating_count: 420,
    expected_output: 'A 10-slide pitch deck narrative with talking points and visual suggestions for each slide.',
    tips: 'Keep each slide to one key message. Investors spend 30 seconds per slide on average.',
  },
  {
    slug: 'python-debugger',
    title: 'Python Debug Assistant',
    description: 'Debug Python code with detailed error analysis, fix suggestions, and best practice recommendations.',
    content: 'You are a Python debugging expert. I have the following Python code that has an issue:\n\n```\n[PASTE YOUR PYTHON CODE]\n```\n\nThe error message or unexpected behavior is: [DESCRIBE THE PROBLEM]\n\nPlease:\n1. Identify the root cause of the issue\n2. Provide the corrected code\n3. Explain what was wrong and why the fix works\n4. Suggest any improvements to prevent similar issues\n5. If there are multiple possible causes, list them in order of likelihood',
    category: 'programming',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['python', 'debugging', 'programming', 'fix'],
    author_name: 'CodeDoctor',
    author_avatar: '🐍',
    featured: false,
    trending: true,
    copies_count: 13800,
    likes_count: 3600,
    rating_avg: 4.7,
    rating_count: 890,
    expected_output: 'A detailed debugging report with root cause, fix, explanation, and prevention tips.',
    tips: 'Include the full error traceback for the most accurate diagnosis.',
  },
  {
    slug: 'youtube-script-master',
    title: 'YouTube Script Master',
    description: 'Generate complete YouTube video scripts with hooks, storytelling, and engagement-boosting techniques.',
    content: 'Write a YouTube video script for the topic: [TOPIC]. Video length: [DURATION]. Channel niche: [NICHE]. Target audience: [AUDIENCE]. Tone: [TONE]. Structure the script as:\n\n1. HOOK (0:00-0:10): An attention-grabbing opening that makes viewers want to keep watching\n2. INTRO (0:10-0:30): Briefly introduce the topic and what viewers will learn\n3. MAIN CONTENT: Break into 3-5 clear sections with natural transitions\n4. B-ROLL SUGGESTIONS: Suggest visual elements for each section\n5. ENGAGEMENT POINTS: Where to ask for likes/comments\n6. OUTRO: Summary and call-to-action (subscribe, watch next video)\n\nInclude estimated timestamps for each section.',
    category: 'video',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['youtube', 'script', 'video', 'content-creation'],
    author_name: 'VideoStar',
    author_avatar: '🎬',
    featured: false,
    trending: true,
    copies_count: 10200,
    likes_count: 2900,
    rating_avg: 4.6,
    rating_count: 650,
    expected_output: 'A complete YouTube script with timestamps, b-roll suggestions, and engagement points.',
    tips: 'The hook is the most important part. 70% of viewers decide to stay in the first 10 seconds.',
  },
  {
    slug: 'product-description-magnet',
    title: 'Product Description That Sells',
    description: 'Write product descriptions that highlight benefits, create desire, and drive purchases.',
    content: 'Write a product description for: [PRODUCT NAME]. Category: [CATEGORY]. Key features: [LIST FEATURES]. Target customer: [TARGET BUYER]. Price range: [PRICE]. Unique selling point: [USP]. Write 3 versions:\n1. Short version (50 words) for quick browsing\n2. Medium version (150 words) for product pages\n3. Long version (300 words) for detailed listings\n\nEach version should:\n- Lead with the main benefit, not the feature\n- Use sensory and emotional language\n- Include social proof elements\n- End with a clear call-to-action\n- Be optimized for the keyword: [KEYWORD]',
    category: 'sales',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['ecommerce', 'product', 'copywriting', 'sales'],
    author_name: 'CopyWizard',
    author_avatar: '🛍️',
    featured: false,
    trending: false,
    copies_count: 7600,
    likes_count: 2200,
    rating_avg: 4.5,
    rating_count: 530,
    expected_output: 'Three product descriptions of varying lengths, all benefit-driven and SEO-optimized.',
    tips: 'Focus on benefits over features. Customers buy outcomes, not specifications.',
  },
  {
    slug: 'study-plan-generator',
    title: 'Personalized Study Plan',
    description: 'Create a structured study plan for any subject with daily schedules, resources, and progress tracking.',
    content: 'Create a personalized study plan for: [SUBJECT/TOPIC]. Current level: [BEGINNER/INTERMEDIATE/ADVANCED]. Goal: [WHAT YOU WANT TO ACHIEVE]. Available time: [HOURS PER WEEK]. Deadline: [DATE]. Learning style: [VISUAL/AUDITORY/KINESTHETIC/READING]. Provide:\n1. A weekly schedule with specific topics for each day\n2. Recommended free resources (videos, articles, courses)\n3. Practice exercises or projects for each week\n4. Milestone checkpoints to measure progress\n5. Revision strategy for long-term retention\n6. Tips to stay motivated and avoid burnout',
    category: 'education',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['study', 'learning', 'education', 'productivity'],
    author_name: 'StudyCoach',
    author_avatar: '📚',
    featured: false,
    trending: false,
    copies_count: 5400,
    likes_count: 1600,
    rating_avg: 4.7,
    rating_count: 380,
    expected_output: 'A detailed weekly study plan with resources, exercises, and milestones.',
    tips: 'Be honest about your available time for a realistic plan you can actually follow.',
  },
  {
    slug: 'legal-contract-analyzer',
    title: 'Contract Risk Analyzer',
    description: 'Analyze legal contracts for risky clauses, hidden fees, and unfavorable terms before you sign.',
    content: 'You are a legal contract analyst. Review the following contract and identify:\n1. Unusual or risky clauses\n2. Hidden fees or costs\n3. Unfavorable terms (liability, termination, IP rights)\n4. Missing standard protections\n5. Ambiguous language that could be exploited\n6. Recommendations for negotiation\n\nFor each finding, explain:\n- What the clause says in plain English\n- Why it is potentially risky\n- What a more favorable version would look like\n\nContract text:\n[PASTE CONTRACT HERE]',
    category: 'legal',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Advanced',
    tags: ['legal', 'contracts', 'risk-analysis', 'review'],
    author_name: 'LegalEagle',
    author_avatar: '⚖️',
    featured: false,
    trending: false,
    copies_count: 3200,
    likes_count: 1100,
    rating_avg: 4.6,
    rating_count: 240,
    expected_output: 'A plain-English contract risk report with specific clause analysis and negotiation recommendations.',
    tips: 'This is for informational purposes only. Always consult a licensed attorney for legal advice.',
  },
  {
    slug: 'financial-model-builder',
    title: 'Financial Model Builder',
    description: 'Build financial projections and models for business planning, fundraising, and forecasting.',
    content: 'Create a financial model for: [BUSINESS TYPE]. Revenue model: [SUBSCRIPTION/ONE-TIME/USAGE-BASED/FREEMIUM]. Initial investment: [AMOUNT]. Monthly expenses: [LIST EXPENSES]. Growth assumptions: [GROWTH RATE]. Time horizon: [MONTHS/YEARS]. Provide:\n1. Monthly revenue projections (conservative, base, optimistic)\n2. Expense breakdown and cost structure\n3. Cash flow statement\n4. Break-even analysis\n5. Key financial metrics (MRR, CAC, LTV, gross margin)\n6. Sensitivity analysis for key variables\n7. Charts description for visualization\n\nFormat as a table that can be copied to a spreadsheet.',
    category: 'finance',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Advanced',
    tags: ['finance', 'financial-model', 'business', 'projections'],
    author_name: 'FinanceWiz',
    author_avatar: '💰',
    featured: false,
    trending: false,
    copies_count: 4100,
    likes_count: 1400,
    rating_avg: 4.5,
    rating_count: 310,
    expected_output: 'A structured financial model with projections, metrics, and sensitivity analysis.',
    tips: 'Use conservative growth assumptions. Overly optimistic projections reduce credibility with investors.',
  },
  {
    slug: 'resume-optimizer',
    title: 'Resume Optimizer Pro',
    description: 'Optimize your resume for ATS systems and recruiters. Get keyword matching and formatting suggestions.',
    content: 'Optimize my resume for the following job description. Resume:\n[PASTE RESUME]\n\nJob Description:\n[PASTE JOB DESCRIPTION]\n\nProvide:\n1. ATS compatibility score (0-100) and issues found\n2. Missing keywords from the job description\n3. Suggestions to rephrase bullet points for impact (use action verbs + metrics)\n4. Formatting recommendations\n5. Sections that need improvement\n6. A revised version of weak bullet points\n7. Overall strengths and weaknesses assessment',
    category: 'resume',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['resume', 'job-search', 'career', 'ats'],
    author_name: 'CareerCoach',
    author_avatar: '📄',
    featured: true,
    trending: false,
    copies_count: 16700,
    likes_count: 4500,
    rating_avg: 4.8,
    rating_count: 1100,
    expected_output: 'A detailed resume analysis with ATS score, keyword gaps, and rewritten bullet points.',
    tips: 'Remove personal info (name, address, phone) before pasting for privacy.',
  },
  {
    slug: 'interview-prep-coach',
    title: 'Interview Prep Coach',
    description: 'Prepare for any job interview with mock questions, answer frameworks, and confidence-building strategies.',
    content: 'Act as an interview coach. I am preparing for a [JOB TITLE] interview at [COMPANY TYPE]. My experience level: [YEARS]. Key skills: [LIST SKILLS]. Provide:\n1. 15 likely interview questions (mix of behavioral and technical)\n2. For each question, a suggested answer framework using the STAR method\n3. Questions I should ask the interviewer\n4. Common mistakes to avoid for this role\n5. A preparation checklist for the 24 hours before the interview\n6. Salary negotiation tips for this role\n7. Follow-up email template for after the interview',
    category: 'interview',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['interview', 'job-search', 'career', 'preparation'],
    author_name: 'InterviewAce',
    author_avatar: '🎯',
    featured: false,
    trending: true,
    copies_count: 9300,
    likes_count: 2700,
    rating_avg: 4.7,
    rating_count: 620,
    expected_output: 'A comprehensive interview prep guide with questions, frameworks, and strategies.',
    tips: 'Practice your answers out loud. Confidence comes from repetition.',
  },
  {
    slug: 'flux-photorealistic',
    title: 'Flux Photorealistic Master',
    description: 'Generate photorealistic image prompts for Flux with precise control over style, lighting, and detail.',
    content: 'Create a photorealistic image prompt for Flux. Subject: [SUBJECT]. Style: ultra-realistic, 8K, professional photography. Camera: [CAMERA MODEL - e.g., Canon EOS R5, Sony A7R IV]. Lens: [LENS - e.g., 85mm f/1.4, 24-70mm f/2.8]. Lighting: [LIGHTING - e.g., natural window light, studio softbox, golden hour]. Setting: [ENVIRONMENT]. Mood: [MOOD]. Color treatment: [COLOR GRADE]. Additional details: [SPECIFIC DETAILS]. Emphasize: realistic skin texture, natural depth of field, professional color grading.',
    category: 'flux',
    ai_models: ['flux', 'stable-diffusion'],
    difficulty: 'Intermediate',
    tags: ['flux', 'photorealistic', 'image-generation', 'ai-art'],
    author_name: 'PixelMaster',
    author_avatar: '🖼️',
    featured: false,
    trending: false,
    copies_count: 5200,
    likes_count: 1600,
    rating_avg: 4.6,
    rating_count: 380,
    expected_output: 'A detailed Flux prompt that generates photorealistic images with professional quality.',
    tips: 'Include specific camera and lens details for more realistic results.',
  },
  {
    slug: 'marketing-campaign-strategist',
    title: 'Marketing Campaign Strategist',
    description: 'Create complete marketing campaign strategies with channels, messaging, budget allocation, and KPIs.',
    content: 'Create a comprehensive marketing campaign for: [PRODUCT/SERVICE]. Target audience: [AUDIENCE]. Budget: [AMOUNT]. Duration: [TIMEFRAME]. Primary goal: [GOAL - e.g., brand awareness, lead gen, sales]. Provide:\n1. Campaign theme and key message\n2. Channel strategy (social, email, paid ads, content, PR) with budget allocation\n3. Content calendar for the campaign duration\n4. Ad creative concepts (3 variations)\n5. Email sequence outline (5 emails)\n6. Landing page recommendations\n7. KPIs and success metrics for each channel\n8. Timeline with milestones and deadlines\n9. Post-campaign analysis framework',
    category: 'marketing',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Advanced',
    tags: ['marketing', 'campaign', 'strategy', 'advertising'],
    author_name: 'MarketingMaven',
    author_avatar: '📣',
    featured: true,
    trending: false,
    copies_count: 6800,
    likes_count: 1900,
    rating_avg: 4.7,
    rating_count: 450,
    expected_output: 'A complete marketing campaign plan with channel strategy, content calendar, and KPIs.',
    tips: 'Start with your goal and work backwards. Every channel should connect to the primary objective.',
  },
  {
    slug: 'productivity-system-designer',
    title: 'Personal Productivity System',
    description: 'Design a complete productivity system tailored to your work style, goals, and schedule.',
    content: 'Design a personalized productivity system for me. My role: [JOB TITLE]. Work style: [DEEP WORK/COLLABORATIVE/MULTITASKING]. Biggest challenges: [LIST CHALLENGES]. Work hours: [SCHEDULE]. Tools I currently use: [LIST TOOLS]. Goals: [LIST GOALS]. Provide:\n1. A daily routine template (morning, deep work, meetings, admin, shutdown)\n2. Weekly review checklist\n3. Task management framework (capture, clarify, organize, reflect, engage)\n4. Meeting management strategy\n5. Energy management tips (when to do what type of work)\n6. Recommended tools and integrations\n7. Templates for daily/weekly planning\n8. Habit stacking suggestions\n9. Quarterly review framework',
    category: 'productivity',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['productivity', 'system', 'habits', 'time-management'],
    author_name: 'ProductivityPro',
    author_avatar: '⚡',
    featured: false,
    trending: true,
    copies_count: 7100,
    likes_count: 2100,
    rating_avg: 4.6,
    rating_count: 540,
    expected_output: 'A complete productivity system with daily routines, frameworks, and tool recommendations.',
    tips: 'Start simple. Add complexity only when the basics become automatic.',
  },
  {
    slug: 'design-system-generator',
    title: 'Design System Generator',
    description: 'Generate a complete design system with color palette, typography, spacing, and component guidelines.',
    content: 'Create a design system for: [PRODUCT TYPE - e.g., SaaS dashboard, mobile app, e-commerce site]. Brand personality: [PERSONALITY TRAITS]. Reference brands: [LIST BRANDS YOU ADMIRE]. Provide:\n1. Color palette: primary, secondary, accent, semantic (success, warning, error, info) with hex codes and usage guidelines\n2. Typography scale: font families, sizes, weights, line heights for headings and body\n3. Spacing system: base unit and scale (4px, 8px, 16px, 24px, 32px, 48px, 64px)\n4. Border radius scale\n5. Shadow system (3 levels)\n6. Component guidelines: buttons, inputs, cards, modals, navigation\n7. Accessibility guidelines (contrast ratios, focus states)\n8. Dark mode color mappings\n9. Design tokens in CSS variable format',
    category: 'design',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Advanced',
    tags: ['design-system', 'ui-design', 'colors', 'typography'],
    author_name: 'DesignArchitect',
    author_avatar: '🎨',
    featured: false,
    trending: false,
    copies_count: 4300,
    likes_count: 1500,
    rating_avg: 4.8,
    rating_count: 340,
    expected_output: 'A structured design system document with color palette, typography, spacing, and component specs.',
    tips: 'Use the CSS variables directly in your project for instant implementation.',
  },
  {
    slug: 'n8n-workflow-architect',
    title: 'n8n Workflow Architect',
    description: 'Design automation workflows for n8n with node configurations, triggers, and error handling.',
    content: 'Design an n8n automation workflow for: [AUTOMATION GOAL]. Trigger: [TRIGGER - e.g., new email, form submission, schedule]. Input data: [DATA FORMAT]. Desired output: [OUTPUT GOAL]. Services to connect: [LIST SERVICES]. Provide:\n1. Workflow architecture diagram (describe nodes and connections)\n2. Each node configuration (node type, parameters, credentials needed)\n3. Data transformation steps between nodes\n4. Error handling strategy (retry, notification, fallback)\n5. Testing checklist\n6. Performance optimization tips\n7. Security considerations\n8. Export-ready JSON structure description',
    category: 'n8n',
    ai_models: ['chatgpt', 'claude'],
    difficulty: 'Advanced',
    tags: ['n8n', 'automation', 'workflow', 'integration'],
    author_name: 'AutomationAce',
    author_avatar: '🔄',
    featured: false,
    trending: false,
    copies_count: 2100,
    likes_count: 800,
    rating_avg: 4.5,
    rating_count: 180,
    expected_output: 'A detailed n8n workflow design with node configurations and error handling.',
    tips: 'Start with a simple version of the workflow and add complexity incrementally.',
  },
  {
    slug: 'health-meal-planner',
    title: 'AI Meal Planner',
    description: 'Create personalized meal plans based on dietary preferences, health goals, and budget.',
    content: 'Create a weekly meal plan for me. Dietary preferences: [DIET - e.g., vegan, keto, Mediterranean]. Allergies: [LIST]. Health goal: [GOAL - e.g., weight loss, muscle gain, maintenance]. Daily calories: [TARGET]. Meals per day: [NUMBER]. Cooking time available: [TIME]. Budget: [AMOUNT PER WEEK]. Provide:\n1. 7-day meal plan with breakfast, lunch, dinner, and snacks\n2. Grocery list organized by store section\n3. Meal prep guide (what to prep on Sunday)\n4. Macro breakdown for each day\n5. Simple recipes for each meal (under 30 minutes)\n6. Substitution options for each meal\n7. Estimated cost per meal',
    category: 'health',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['health', 'meal-plan', 'nutrition', 'wellness'],
    author_name: 'HealthCoach',
    author_avatar: '🥗',
    featured: false,
    trending: false,
    copies_count: 8900,
    likes_count: 2500,
    rating_avg: 4.6,
    rating_count: 620,
    expected_output: 'A 7-day meal plan with recipes, grocery list, and nutritional info.',
    tips: 'Batch cook grains and proteins on Sunday to save time during the week.',
  },
];
