import type { SeedPrompt } from './prompt-data';

export const SEED_PROMPTS_BATCH_3: SeedPrompt[] = [
  {
    slug: 'api-documentation-writer',
    title: 'API Documentation Writer',
    description: 'Generate clear, comprehensive API documentation from code or OpenAPI specs.',
    content: 'You are a technical writer specializing in API documentation. Generate documentation for the following API:\n\n[API SPEC OR CODE]\n\nProvide:\n1. API overview and authentication method\n2. Base URL and versioning\n3. Endpoint reference table (method, path, description)\n4. Detailed documentation for each endpoint:\n   - Description\n   - HTTP method and path\n   - Required and optional parameters\n   - Request example (curl + JSON body)\n   - Response examples (success + error)\n   - Status codes\n5. Rate limiting info\n6. Error handling guide\n7. SDK usage examples (JavaScript and Python)',
    category: 'programming',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['api', 'documentation', 'technical-writing', 'developer'],
    author_name: 'DocWriter',
    author_avatar: '📚',
    featured: false,
    trending: false,
    copies_count: 3400,
    likes_count: 1100,
    rating_avg: 4.6,
    rating_count: 240,
    expected_output: 'Complete API documentation with endpoint details, examples, and error handling.',
    tips: 'Include your OpenAPI/Swagger spec for the most accurate documentation.',
  },
  {
    slug: 'social-media-calendar-30day',
    title: '30-Day Social Media Calendar',
    description: 'Generate a complete 30-day social media content calendar across multiple platforms.',
    content: 'Create a 30-day social media content calendar. Platforms: [LIST PLATFORMS]. Niche: [NICHE]. Posting frequency: [POSTS PER DAY PER PLATFORM]. Content pillars: [LIST 3-5 THEMES]. Provide:\n1. Content strategy overview\n2. 30-day calendar with daily posts for each platform:\n   - Post type (image, video, carousel, story, reel)\n   - Topic and brief description\n   - Caption outline\n   - Hashtag set (10-15 per post)\n   - Best posting time\n3. Weekly theme breakdown\n4. Content repurposing strategy\n5. Engagement strategy (comment, DM, community)\n6. Monthly campaign idea\n7. Content creation batch schedule',
    category: 'social-media',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['social-media', 'calendar', 'content-planning', 'strategy'],
    author_name: 'CalendarQueen',
    author_avatar: '📅',
    featured: false,
    trending: false,
    copies_count: 5100,
    likes_count: 1600,
    rating_avg: 4.5,
    rating_count: 370,
    expected_output: 'A 30-day multi-platform social media calendar with daily post ideas and captions.',
    tips: 'Batch create content on weekends. Schedule posts for the whole week to stay consistent.',
  },
  {
    slug: 'startup-name-generator',
    title: 'Startup Name Generator',
    description: 'Generate memorable, brandable startup names with domain availability and trademark considerations.',
    content: 'Generate startup name ideas for: [BUSINESS DESCRIPTION]. Industry: [INDUSTRY]. Style preference: [SHORT/MEMORABLE/DESCRIPTIVE/ABSTRACT]. Target audience: [AUDIENCE]. Provide 20 name ideas organized by category:\n1. Blended words (5)\n2. Made-up/abstract names (5)\n3. Evocative names (5)\n4. Descriptive names (5)\n\nFor each name:\n- Brief explanation of meaning/inspiration\n- Potential domain availability (.com, .io, .ai, .co)\n- Trademark risk level (low/medium/high)\n- Brand potential score (1-10)\n\nThen recommend the top 3 names with reasoning.',
    category: 'business',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['naming', 'startup', 'branding', 'domains'],
    author_name: 'NameNinja',
    author_avatar: '🏷️',
    featured: false,
    trending: false,
    copies_count: 6200,
    likes_count: 1800,
    rating_avg: 4.4,
    rating_count: 420,
    expected_output: '20 categorized startup name ideas with domain and trademark analysis.',
    tips: 'Check domain availability immediately. Good names get taken fast.',
  },
  {
    slug: 'email-welcome-sequence',
    title: 'Welcome Email Sequence Builder',
    description: 'Create high-converting welcome email sequences that nurture subscribers and drive engagement.',
    content: 'Create a welcome email sequence for: [BUSINESS/PRODUCT]. Audience: [TARGET]. Goal: [EDUCATE/SELL/ENGAGE]. Sequence length: [NUMBER OF EMAILS]. Provide:\n1. Sequence strategy overview\n2. For each email:\n   - Send timing (immediate, +1 day, +3 days, etc.)\n   - Subject line (2 variations for A/B testing)\n   - Preview text\n   - Email body (full copy)\n   - CTA\n   - Personalization tokens\n3. Segmentation strategy (behavior-based splits)\n4. Engagement triggers (opens, clicks, conversions)\n5. Re-engagement for non-openers\n6. Metrics to track\n7. Optimization recommendations',
    category: 'email',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['email', 'welcome-sequence', 'nurture', 'automation'],
    author_name: 'EmailExpert',
    author_avatar: '✉️',
    featured: false,
    trending: false,
    copies_count: 4300,
    likes_count: 1400,
    rating_avg: 4.6,
    rating_count: 310,
    expected_output: 'A complete welcome email sequence with full copy, timing, and A/B subject lines.',
    tips: 'The first email should arrive immediately. Delay reduces open rates by 50%+.',
  },
  {
    slug: 'gemini-image-analyzer',
    title: 'Gemini Image Analyzer',
    description: 'Analyze images with Gemini for content, context, accessibility, and improvement suggestions.',
    content: 'Analyze the following image description or uploaded image. Provide:\n1. Content description (what is in the image)\n2. Context and setting\n3. Color palette analysis\n4. Composition assessment\n5. Mood and emotion conveyed\n6. Accessibility description (alt text)\n7. SEO optimization (if for web content)\n8. Improvement suggestions (3-5)\n9. Similar image concepts for inspiration\n10. Potential use cases for this image\n\nImage: [DESCRIBE OR UPLOAD IMAGE]',
    category: 'gemini',
    ai_models: ['gemini', 'chatgpt'],
    difficulty: 'Beginner',
    tags: ['gemini', 'image-analysis', 'accessibility', 'vision'],
    author_name: 'VisionAI',
    author_avatar: '👁️',
    featured: false,
    trending: false,
    copies_count: 2800,
    likes_count: 900,
    rating_avg: 4.5,
    rating_count: 190,
    expected_output: 'A comprehensive image analysis with alt text, SEO suggestions, and improvement tips.',
    tips: 'Gemini\'s multimodal capabilities make it ideal for image analysis tasks.',
  },
  {
    slug: 'claude-creative-writing',
    title: 'Claude Creative Writing Partner',
    description: 'Advanced creative writing assistant for novels, poetry, and screenplays with style matching.',
    content: 'You are my creative writing partner. Genre: [GENRE]. My writing style: [DESCRIBE YOUR STYLE]. Current project: [DESCRIBE]. What I need help with: [BRAINSTORMING/DRAFTING/EDITING/DIALOGUE/DESCRIPTION]. Provide:\n1. Three creative directions for the scene/chapter\n2. For the best direction, write a 500-word draft\n3. Alternative dialogue options for key lines\n4. Sensory detail suggestions (sight, sound, smell, touch, taste)\n5. Pacing recommendations\n6. Character voice consistency notes\n7. Tension and conflict escalation ideas\n8. Suggestions for "show, don\'t tell" improvements\n\nMatch my writing style and voice. Be a collaborator, not just a generator.',
    category: 'claude',
    ai_models: ['claude', 'chatgpt'],
    difficulty: 'Advanced',
    tags: ['creative-writing', 'claude', 'fiction', 'storytelling'],
    author_name: 'Wordsmith',
    author_avatar: '✒️',
    featured: false,
    trending: false,
    copies_count: 3900,
    likes_count: 1300,
    rating_avg: 4.8,
    rating_count: 280,
    expected_output: 'Creative writing assistance with drafts, dialogue options, and style-matched suggestions.',
    tips: 'Share a sample of your writing first so Claude can match your unique voice.',
  },
  {
    slug: 'chatgpt-data-extractor',
    title: 'ChatGPT Data Extractor',
    description: 'Extract structured data from unstructured text. Parse emails, invoices, reports into clean formats.',
    content: 'You are a data extraction specialist. Extract structured data from the following unstructured text:\n\n[TEXT TO PARSE]\n\nDesired output format: [JSON/CSV/TABLE]\nFields to extract: [LIST FIELDS OR "AUTO-DETECT"]\n\nProvide:\n1. Extracted data in the requested format\n2. Confidence level for each extracted field (high/medium/low)\n3. Fields that could not be extracted and why\n4. Data quality issues found\n5. Cleaned and normalized version\n6. Suggestions for improving the source data\n7. Regex patterns that could automate this extraction',
    category: 'chatgpt',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['data-extraction', 'parsing', 'automation', 'chatgpt'],
    author_name: 'DataMiner',
    author_avatar: '⛏️',
    featured: false,
    trending: true,
    copies_count: 5600,
    likes_count: 1700,
    rating_avg: 4.6,
    rating_count: 390,
    expected_output: 'Structured data extraction with confidence scores and quality assessment.',
    tips: 'Provide the output format explicitly for consistent results.',
  },
  {
    slug: 'midjourney-character-design',
    title: 'Character Design Studio',
    description: 'Create detailed character design prompts for Midjourney with consistent style across multiple poses.',
    content: 'Create a character design prompt set for Midjourney. Character: [CHARACTER DESCRIPTION]. Art style: [ANIME/REALISTIC/CARTOON/PIXAR/COMIC]. Color scheme: [COLORS]. Provide 5 prompts:\n1. Full body character sheet (front view)\n2. Character turnaround (front, side, back)\n3. Action pose\n4. Facial expression sheet (5 expressions)\n5. Character in their environment\n\nEach prompt should maintain visual consistency using the same style descriptors. Include seed recommendation for consistency. Add --ar and --style parameters.',
    category: 'midjourney',
    ai_models: ['midjourney', 'stable-diffusion', 'flux'],
    difficulty: 'Advanced',
    tags: ['character-design', 'midjourney', 'concept-art', 'illustration'],
    author_name: 'CharacterArt',
    author_avatar: '🧙',
    featured: false,
    trending: false,
    copies_count: 3700,
    likes_count: 1200,
    rating_avg: 4.7,
    rating_count: 260,
    expected_output: 'Five consistent character design prompts with style continuity across poses.',
    tips: 'Use the same --seed value across prompts for maximum visual consistency.',
  },
  {
    slug: 'productivity-meeting-notes',
    title: 'AI Meeting Notes Processor',
    description: 'Transform raw meeting transcripts into structured notes with action items, decisions, and summaries.',
    content: 'You are a meeting notes assistant. Process the following meeting transcript/notes:\n\n[MEETING TRANSCRIPT OR RAW NOTES]\n\nProvide:\n1. Meeting summary (3-5 sentences)\n2. Key decisions made\n3. Action items (assignee, task, deadline)\n4. Discussion topics with key points\n5. Parking lot items (mentioned but not resolved)\n6. Questions that need follow-up\n7. Risk or concern flags\n8. Next meeting agenda suggestions\n9. Formatted email summary ready to send to attendees',
    category: 'productivity',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['meetings', 'notes', 'productivity', 'summarization'],
    author_name: 'MeetingMaster',
    author_avatar: '📝',
    featured: false,
    trending: true,
    copies_count: 8400,
    likes_count: 2400,
    rating_avg: 4.7,
    rating_count: 580,
    expected_output: 'Structured meeting notes with action items, decisions, and a ready-to-send summary email.',
    tips: 'Paste raw notes or a transcript. The AI will organize everything into a clean structure.',
  },
  {
    slug: 'legal-privacy-policy',
    title: 'Privacy Policy Generator',
    description: 'Generate GDPR and CCPA-compliant privacy policies for websites and apps.',
    content: 'Generate a privacy policy for: [WEBSITE/APP NAME]. Business type: [E-COMMERCE/SaaS/BLOG/APP]. Data collected: [LIST DATA TYPES]. Third-party services: [LIST - e.g., Google Analytics, Stripe, Mailchimp]. User location: [GLOBAL/EU/US/CALIFORNIA]. Provide:\n1. Complete privacy policy including:\n   - Introduction and scope\n   - Information we collect\n   - How we use information\n   - Legal basis for processing (GDPR)\n   - Cookies and tracking technologies\n   - Third-party data sharing\n   - Data retention policy\n   - User rights (access, deletion, portability)\n   - Children\'s privacy\n   - International data transfers\n   - Policy updates\n   - Contact information\n2. Cookie policy section\n3. Summary for non-legal readers\n\nDisclaimer: This is a template. Have a lawyer review before publishing.',
    category: 'legal',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['legal', 'privacy', 'gdpr', 'compliance'],
    author_name: 'LegalTech',
    author_avatar: '🔒',
    featured: false,
    trending: false,
    copies_count: 4100,
    likes_count: 1300,
    rating_avg: 4.4,
    rating_count: 280,
    expected_output: 'A complete privacy policy document with GDPR/CCPA compliance sections.',
    tips: 'List all third-party tools you use. Missing one can create compliance gaps.',
  },
  {
    slug: 'finance-budget-forecaster',
    title: 'Personal Budget Forecaster',
    description: 'Create detailed personal budget forecasts with savings goals and investment scenarios.',
    content: 'Create a personal financial plan. Monthly income: [AMOUNT]. Fixed expenses: [LIST]. Variable expenses: [LIST]. Savings goal: [AMOUNT by DATE]. Current savings: [AMOUNT]. Debt: [LIST with INTEREST RATES]. Risk tolerance: [CONSERVATIVE/MODERATE/AGGRESSIVE]. Provide:\n1. Monthly budget breakdown (50/30/20 rule customized)\n2. Debt payoff strategy (avalanche vs. snowball)\n3. Savings rate analysis\n4. 12-month projection with 3 scenarios (conservative, base, optimistic)\n5. Investment allocation recommendation\n6. Emergency fund plan\n7. Insurance coverage assessment\n8. Retirement projection (if applicable)\n9. Financial independence timeline\n10. Monthly action checklist',
    category: 'finance',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['finance', 'budget', 'forecasting', 'personal-finance'],
    author_name: 'MoneyMentor',
    author_avatar: '💵',
    featured: false,
    trending: false,
    copies_count: 5200,
    likes_count: 1600,
    rating_avg: 4.5,
    rating_count: 380,
    expected_output: 'A detailed personal financial plan with budget, debt strategy, and 12-month projections.',
    tips: 'Be honest about your spending. Underestimating expenses leads to unrealistic plans.',
  },
  {
    slug: 'design-color-palette-pro',
    title: 'Color Palette Generator Pro',
    description: 'Generate professional color palettes with accessibility checks and usage guidelines.',
    content: 'Generate a color palette for: [PROJECT TYPE]. Brand personality: [PERSONALITY]. Reference: [BRANDS YOU LIKE]. Mood: [MOOD]. Provide:\n1. Primary palette (5 colors with hex, RGB, HSL)\n2. Extended palette (10 additional shades/tints)\n3. Semantic colors (success, warning, error, info)\n4. Neutral colors (backgrounds, text, borders)\n5. Dark mode equivalents\n6. Accessibility check:\n   - WCAG AA contrast ratios for all text/background combinations\n   - Color blind safe alternatives\n7. Usage guidelines (when to use each color)\n8. CSS variables ready to copy\n9. Tailwind config format\n10. Gradient suggestions (3 combinations)',
    category: 'design',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['color-palette', 'design-system', 'accessibility', 'branding'],
    author_name: 'ColorCrafter',
    author_avatar: '🎨',
    featured: false,
    trending: true,
    copies_count: 6800,
    likes_count: 2000,
    rating_avg: 4.7,
    rating_count: 460,
    expected_output: 'A complete color palette with accessibility checks, CSS variables, and Tailwind config.',
    tips: 'Test your palette on real designs. Colors look different in context vs. isolation.',
  },
  {
    slug: 'education-lesson-planner',
    title: 'AI Lesson Plan Creator',
    description: 'Create detailed lesson plans for any subject, grade level, and teaching style.',
    content: 'Create a lesson plan for: [SUBJECT/TOPIC]. Grade level: [GRADE]. Duration: [MINUTES]. Class size: [NUMBER]. Learning objectives: [LIST]. Teaching style: [LECTURE/INTERACTIVE/PROJECT-BASED/FLIPPED]. Provide:\n1. Lesson overview and objectives\n2. Materials needed\n3. Hook/opening activity (5 minutes)\n4. Main activity breakdown (with timing)\n5. Differentiated instruction strategies\n6. Group work or pair activities\n7. Assessment/exit ticket\n8. Homework assignment\n9. Extension activities for advanced students\n10. Modifications for special needs\n11. Technology integration suggestions\n12. Standards alignment',
    category: 'education',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['education', 'lesson-plan', 'teaching', 'classroom'],
    author_name: 'TeacherAI',
    author_avatar: '🎓',
    featured: false,
    trending: false,
    copies_count: 4700,
    likes_count: 1500,
    rating_avg: 4.6,
    rating_count: 340,
    expected_output: 'A complete lesson plan with activities, assessments, and differentiation strategies.',
    tips: 'Include your state/national standards for automatic alignment suggestions.',
  },
  {
    slug: 'marketing-ab-test-planner',
    title: 'A/B Test Planner',
    description: 'Design statistically sound A/B tests with hypothesis, sample size, and success metrics.',
    content: 'Design an A/B test for: [WHAT YOU WANT TO TEST]. Current metric value: [CURRENT RATE]. Minimum detectable effect: [PERCENTAGE]. Traffic: [VISITORS PER MONTH]. Confidence level: [95%/99%]. Provide:\n1. Test hypothesis (null and alternative)\n2. Primary and secondary metrics\n3. Sample size calculation\n4. Test duration estimate\n5. Variant descriptions (A: control, B: treatment)\n6. Segmentation strategy\n7. Potential confounding variables\n8. Success criteria\n9. Failure criteria and what to do\n10. Post-test analysis plan\n11. Implementation checklist\n12. Risk assessment',
    category: 'marketing',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Advanced',
    tags: ['ab-testing', 'optimization', 'experimentation', 'marketing'],
    author_name: 'TestTactician',
    author_avatar: '🧪',
    featured: false,
    trending: false,
    copies_count: 3200,
    likes_count: 1100,
    rating_avg: 4.6,
    rating_count: 230,
    expected_output: 'A complete A/B test plan with hypothesis, sample size, and analysis framework.',
    tips: 'Test one variable at a time. Multiple changes make it impossible to attribute results.',
  },
  {
    slug: 'resume-linkedIn-optimizer',
    title: 'LinkedIn Profile Optimizer',
    description: 'Optimize your LinkedIn profile for recruiters with keyword analysis and content suggestions.',
    content: 'Optimize my LinkedIn profile for [TARGET ROLE/INDUSTRY]. Current headline: [HEADLINE]. Current about: [ABOUT TEXT]. Experience: [BRIEF SUMMARY]. Skills: [LIST]. Goals: [WHAT YOU WANT]. Provide:\n1. Optimized headline (3 variations)\n2. Rewritten about section (story-driven, keyword-rich)\n3. Experience section improvements:\n   - Bullet point rewrites with metrics\n   - Action verb suggestions\n4. Skills optimization (add/remove/reorder)\n5. Keyword gap analysis vs. target roles\n6. Profile completeness checklist\n7. Content strategy (what to post for visibility)\n8. Connection strategy (who to connect with)\n9. Endorsement and recommendation strategy\n10. 30-day profile growth plan',
    category: 'career',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['linkedin', 'career', 'optimization', 'personal-branding'],
    author_name: 'ProfilePro',
    author_avatar: '💼',
    featured: false,
    trending: false,
    copies_count: 7300,
    likes_count: 2100,
    rating_avg: 4.6,
    rating_count: 490,
    expected_output: 'A complete LinkedIn optimization guide with rewritten sections and growth plan.',
    tips: 'Your headline appears in search results. Make it keyword-rich, not just your job title.',
  },
  {
    slug: 'coding-refactoring-guide',
    title: 'Code Refactoring Advisor',
    description: 'Analyze code for refactoring opportunities with step-by-step improvement plans.',
    content: 'You are a code refactoring expert. Analyze the following code and provide refactoring recommendations:\n```\n[PASTE YOUR CODE]\n```\nLanguage: [LANGUAGE]. Concerns: [PERFORMANCE/READABILITY/MAINTAINABILITY/TESTABILITY]. Provide:\n1. Code smell assessment (list all found)\n2. Refactoring priority matrix (impact vs. effort)\n3. For each refactoring:\n   - What to change and why\n   - Before and after code\n   - Risk assessment\n   - Testing recommendations\n4. Design pattern suggestions\n5. Dependency analysis\n6. Dead code identification\n7. Performance optimization opportunities\n8. Step-by-step refactoring sequence\n9. Estimated time for each refactoring',
    category: 'coding',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Advanced',
    tags: ['refactoring', 'code-quality', 'clean-code', 'programming'],
    author_name: 'RefactorRanger',
    author_avatar: '🔧',
    featured: false,
    trending: false,
    copies_count: 3600,
    likes_count: 1200,
    rating_avg: 4.7,
    rating_count: 250,
    expected_output: 'A prioritized refactoring plan with before/after code and risk assessment.',
    tips: 'Refactor in small steps and test after each change. Big bang refactoring introduces bugs.',
  },
  {
    slug: 'writing-grammar-coach',
    title: 'Grammar and Style Coach',
    description: 'Improve your writing with grammar corrections, style suggestions, and clarity improvements.',
    content: 'You are a professional editor. Review the following text for grammar, style, and clarity:\n\n[TEXT TO REVIEW]\n\nProvide:\n1. Grammar corrections (list each with explanation)\n2. Style improvements (word choice, sentence structure)\n3. Clarity suggestions (simplify complex sentences)\n4. Tone consistency check\n5. Passive voice instances (with active alternatives)\n6. Wordiness reduction (concise alternatives)\n7. Transition and flow improvements\n8. Readability score assessment\n9. Rewritten version incorporating all suggestions\n10. Summary of key improvements',
    category: 'writing',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['grammar', 'editing', 'writing', 'style'],
    author_name: 'GrammarGuardian',
    author_avatar: '✏️',
    featured: false,
    trending: false,
    copies_count: 9200,
    likes_count: 2600,
    rating_avg: 4.5,
    rating_count: 610,
    expected_output: 'A detailed editing report with grammar fixes, style improvements, and a rewritten version.',
    tips: 'Paste the full text. Partial texts miss context-dependent issues.',
  },
  {
    slug: 'seo-technical-audit',
    title: 'Technical SEO Audit Checklist',
    description: 'Comprehensive technical SEO audit with prioritized fixes for search engine performance.',
    content: 'Perform a technical SEO audit checklist for: [WEBSITE URL OR DESCRIPTION]. Current issues: [KNOWN PROBLEMS]. CMS: [WORDPRESS/SHOPIFY/CUSTOM/etc.]. Provide a prioritized audit:\n1. Crawlability and indexation (robots.txt, sitemap, canonical tags)\n2. Site architecture (URL structure, internal linking, breadcrumbs)\n3. Page speed factors (Core Web Vitals, image optimization, caching)\n4. Mobile optimization (responsive, AMP, mobile-first indexing)\n5. Structured data (schema markup gaps)\n6. HTTPS and security\n7. Duplicate content issues\n8. Redirect chains and broken links\n9. XML sitemap analysis\n10. International SEO (hreflang if applicable)\n\nFor each: status (pass/warning/fail), explanation, and fix instructions.',
    category: 'seo',
    ai_models: ['chatgpt', 'claude', 'gemini', 'perplexity'],
    difficulty: 'Advanced',
    tags: ['technical-seo', 'audit', 'core-web-vitals', 'optimization'],
    author_name: 'SEOAuditor',
    author_avatar: '🔧',
    featured: false,
    trending: false,
    copies_count: 3800,
    likes_count: 1300,
    rating_avg: 4.7,
    rating_count: 290,
    expected_output: 'A comprehensive technical SEO audit with prioritized issues and fix instructions.',
    tips: 'Use Google Search Console data alongside this audit for real-world performance metrics.',
  },
  {
    slug: 'sales-pitch-generator',
    title: 'Sales Pitch Generator',
    description: 'Create compelling sales pitches for any product with psychology-backed persuasion frameworks.',
    content: 'Create a sales pitch for: [PRODUCT/SERVICE]. Audience: [BUYER PERSONA]. Setting: [IN-PERSON/CALL/EMAIL/VIDEO]. Time: [ELEVATOR/2-MIN/10-MIN]. Price: [PRICE]. Provide 3 pitch versions using different frameworks:\n1. Problem-Agitate-Solve (PAS) framework\n2. Features-Advantages-Benefits (FAB) framework\n3. Story-based pitch (hero\'s journey format)\n\nFor each:\n- Full script\n- Key psychological triggers used\n- Objection handling points\n- Close/CTA\n- Follow-up strategy\n\nAlso provide:\n- One-liner elevator pitch\n- Email subject line for follow-up\n- Social proof points to weave in',
    category: 'sales',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['sales', 'pitch', 'persuasion', 'presentation'],
    author_name: 'PitchPerfect',
    author_avatar: '🎤',
    featured: false,
    trending: false,
    copies_count: 4400,
    likes_count: 1400,
    rating_avg: 4.6,
    rating_count: 320,
    expected_output: 'Three sales pitch scripts using different frameworks with objection handling.',
    tips: 'Practice your pitch out loud. Written pitches always feel shorter than they are when spoken.',
  },
  {
    slug: 'health-workout-planner',
    title: 'Personal Workout Planner',
    description: 'Create customized workout plans based on your goals, equipment, and fitness level.',
    content: 'Create a personalized workout plan. Goal: [BUILD MUSCLE/LOSE FAT/ENDURANCE/FLEXIBILITY/GENERAL FITNESS]. Fitness level: [BEGINNER/INTERMEDIATE/ADVANCED]. Available days: [DAYS PER WEEK]. Session length: [MINUTES]. Equipment: [FULL GYM/HOME DUMBBELLS/BODYWEIGHT ONLY]. Injuries/limitations: [LIST]. Provide:\n1. Weekly workout split\n2. For each day:\n   - Warm-up routine (5 minutes)\n   - Main workout (exercises, sets, reps, rest)\n   - Cool-down and stretching\n3. Progressive overload plan (4 weeks)\n4. Cardio recommendations\n5. Mobility and recovery schedule\n6. Nutrition guidelines (not a meal plan)\n7. Tracking metrics\n8. Deload week schedule\n9. Plateau-breaking strategies',
    category: 'health',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['fitness', 'workout', 'exercise', 'health'],
    author_name: 'FitCoach',
    author_avatar: '💪',
    featured: false,
    trending: true,
    copies_count: 7800,
    likes_count: 2300,
    rating_avg: 4.6,
    rating_count: 540,
    expected_output: 'A complete weekly workout plan with exercises, progression, and recovery strategy.',
    tips: 'Start lighter than you think. Consistency beats intensity for long-term results.',
  },
  {
    slug: 'photography-editing-guide',
    title: 'Photo Editing Guide',
    description: 'Get detailed photo editing instructions for Lightroom, Photoshop, or mobile apps.',
    content: 'You are a photo editing expert. I have a photo of: [DESCRIBE PHOTO - subject, lighting, mood]. Editing software: [LIGHTROOM/PHOTOSHOP/SNAPSEED/VSCO]. Desired style: [CINEMATIC/VINTAGE/MINIMAL/BOLD/NATURAL]. Issues to fix: [LIST - e.g., overexposed, color cast, low contrast]. Provide:\n1. Step-by-step editing workflow\n2. Specific settings for each adjustment:\n   - Exposure, contrast, highlights, shadows\n   - Color temperature, tint, vibrance, saturation\n   - HSL panel adjustments\n   - Tone curve recommendations\n   - Sharpening and noise reduction\n3. Local adjustments (radial/linear gradients, brushes)\n4. Preset creation instructions\n5. Before/after expectations\n6. Common mistakes to avoid\n7. Batch editing tips for similar photos',
    category: 'photography',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['photo-editing', 'lightroom', 'post-processing', 'photography'],
    author_name: 'EditExpert',
    author_avatar: '🎚️',
    featured: false,
    trending: false,
    copies_count: 2900,
    likes_count: 1000,
    rating_avg: 4.5,
    rating_count: 210,
    expected_output: 'A step-by-step photo editing guide with specific settings for your editing software.',
    tips: 'Edit on a calibrated monitor if possible. Phone screens are too bright for accurate editing.',
  },
  {
    slug: 'automation-workflow-optimizer',
    title: 'Automation Workflow Optimizer',
    description: 'Analyze and optimize your existing automation workflows for efficiency and reliability.',
    content: 'You are an automation expert. I have the following workflow:\n\n[DESCRIBE YOUR WORKFLOW - tools, steps, triggers, actions]\n\nCurrent issues: [PROBLEMS - slow, failing, expensive, complex]. Goals: [WHAT YOU WANT TO IMPROVE]. Provide:\n1. Workflow analysis (bottlenecks, redundancy, failure points)\n2. Optimization recommendations (prioritized)\n3. Simplified workflow diagram\n4. Tool consolidation suggestions\n5. Error handling improvements\n6. Cost optimization (reduce tasks/runs)\n7. Performance optimization (faster execution)\n8. Scalability assessment\n9. Monitoring and alerting recommendations\n10. Migration plan if switching tools\n11. Testing strategy\n12. Documentation template',
    category: 'automation',
    ai_models: ['chatgpt', 'claude'],
    difficulty: 'Advanced',
    tags: ['automation', 'optimization', 'workflow', 'efficiency'],
    author_name: 'FlowOptimizer',
    author_avatar: '⚙️',
    featured: false,
    trending: false,
    copies_count: 2100,
    likes_count: 800,
    rating_avg: 4.6,
    rating_count: 160,
    expected_output: 'A detailed workflow optimization report with prioritized improvements and migration plan.',
    tips: 'Map your workflow visually first. Diagrams reveal inefficiencies that text descriptions hide.',
  },
  {
    slug: 'interview-behavioral-coach',
    title: 'Behavioral Interview Coach',
    description: 'Master behavioral interviews with STAR method frameworks and practice questions.',
    content: 'You are a behavioral interview coach. Position: [JOB TITLE]. Company type: [STARTUP/ENTERPRISE/AGENCY]. Experience level: [YEARS]. Provide:\n1. 20 behavioral interview questions organized by competency:\n   - Leadership (5)\n   - Problem-solving (5)\n   - Teamwork (5)\n   - Adaptability (5)\n2. For each question:\n   - What the interviewer is really asking\n   - STAR framework template to fill in\n   - Example answer structure\n   - Red flags to avoid\n3. Your stories inventory (list of experiences to prepare)\n4. Common follow-up questions\n5. Questions to ask the interviewer\n6. Body language tips\n7. Virtual interview setup checklist\n8. Post-interview follow-up templates',
    category: 'interview',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['interview', 'behavioral', 'star-method', 'job-search'],
    author_name: 'InterviewIQ',
    author_avatar: '🧠',
    featured: false,
    trending: false,
    copies_count: 5100,
    likes_count: 1600,
    rating_avg: 4.7,
    rating_count: 380,
    expected_output: 'A comprehensive behavioral interview prep guide with 20 questions and STAR frameworks.',
    tips: 'Prepare 5-7 versatile stories that can answer multiple question types.',
  },
  {
    slug: 'excel-dashboard-builder',
    title: 'Excel Dashboard Builder',
    description: 'Create interactive Excel dashboards with charts, KPIs, and data visualization best practices.',
    content: 'You are an Excel dashboard expert. I need a dashboard for: [PURPOSE]. Data source: [DESCRIBE DATA]. Key metrics: [LIST KPIs]. Audience: [WHO WILL USE IT]. Provide:\n1. Dashboard layout plan (sections, placement)\n2. Data preparation steps (cleaning, pivot tables)\n3. Chart recommendations for each metric:\n   - Chart type and why\n   - Data range\n   - Formatting (colors, labels, axes)\n4. Interactive elements:\n   - Slicers and timelines\n   - Drop-down filters\n   - Dynamic chart titles\n5. KPI cards/summary section\n6. Conditional formatting rules\n7. Formula list (SUMIFS, INDEX/MATCH, dynamic ranges)\n8. Color scheme and styling guide\n9. Print and export settings\n10. Maintenance instructions',
    category: 'excel',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Advanced',
    tags: ['excel', 'dashboard', 'data-visualization', 'reporting'],
    author_name: 'DashboardDev',
    author_avatar: '📊',
    featured: false,
    trending: true,
    copies_count: 4200,
    likes_count: 1400,
    rating_avg: 4.6,
    rating_count: 310,
    expected_output: 'A complete Excel dashboard plan with chart recommendations, formulas, and formatting guide.',
    tips: 'Use Excel Tables (Ctrl+T) for your data source. Dashboards auto-update when data changes.',
  },
  {
    slug: 'video-youtube-seo',
    title: 'YouTube SEO Optimizer',
    description: 'Optimize YouTube videos for search with title, description, tags, and thumbnail strategies.',
    content: 'Optimize my YouTube video for search. Topic: [VIDEO TOPIC]. Target keyword: [KEYWORD]. Channel niche: [NICHE]. Audience: [TARGET]. Video length: [MINUTES]. Provide:\n1. Title options (5 variations, under 60 characters, keyword-rich)\n2. Optimized description (first 150 chars for search preview, full description with timestamps, links, keywords)\n3. Tag list (15-20 relevant tags, mix of broad and specific)\n4. Thumbnail text suggestions (3-5 words, high contrast)\n5. Thumbnail design recommendations (colors, composition, emotion)\n6. End screen and card suggestions\n7. Playlist categorization recommendation\n8. Best posting time and day\n9. Community tab post to promote the video\n10. First comment to pin\n11. Related video ideas for a content cluster',
    category: 'video',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['youtube', 'seo', 'optimization', 'video-marketing'],
    author_name: 'TubeGenius',
    author_avatar: '📺',
    featured: false,
    trending: false,
    copies_count: 6300,
    likes_count: 1900,
    rating_avg: 4.6,
    rating_count: 440,
    expected_output: 'A complete YouTube SEO package with titles, description, tags, and thumbnail strategy.',
    tips: 'The first 24 hours are critical. Optimize before publishing, not after.',
  },
  {
    slug: 'chatgpt-prompt-engineer',
    title: 'Meta Prompt Engineer',
    description: 'A prompt that creates optimized prompts. The ultimate prompt engineering tool.',
    content: 'You are an expert prompt engineer. I need a prompt for: [DESCRIBE WHAT YOU WANT THE PROMPT TO DO]. Target AI: [CHATGPT/CLAUDE/GEMINI/MIDJOURNEY]. Desired output format: [FORMAT]. Provide:\n1. The optimized prompt (ready to use)\n2. Explanation of why this prompt structure works\n3. Variables/placeholders I should customize (marked with [BRACKETS])\n4. Example filled-in version\n5. Alternative prompt for different output styles (2 variations)\n6. Tips for getting the best results\n7. Common mistakes to avoid with this prompt\n8. How to iterate if the first result isn\'t perfect',
    category: 'chatgpt',
    ai_models: ['chatgpt', 'claude'],
    difficulty: 'Advanced',
    tags: ['prompt-engineering', 'meta-prompt', 'optimization', 'chatgpt'],
    author_name: 'PromptEngineer',
    author_avatar: '🧙‍♂️',
    featured: true,
    trending: true,
    copies_count: 15600,
    likes_count: 4200,
    rating_avg: 4.9,
    rating_count: 980,
    expected_output: 'An optimized prompt with explanations, examples, and iteration guidance.',
    tips: 'The more specific your description of what you want, the better the generated prompt.',
  },
  {
    slug: 'design-typography-selector',
    title: 'Typography Pairing Generator',
    description: 'Find perfect font pairings for any project with accessibility and brand fit analysis.',
    content: 'Recommend font pairings for: [PROJECT TYPE - website, app, print, brand]. Brand personality: [PERSONALITY]. Style: [MODERN/CLASSIC/PLAYFUL/MINIMAL/BOLD]. Audience: [DEMOGRAPHIC]. Provide 5 font pairings:\n1. For each pairing:\n   - Heading font (name, weight, style)\n   - Body font (name, weight, style)\n   - Why they work together\n   - Google Fonts link or Adobe Fonts equivalent\n   - CSS font-family declaration\n   - Recommended sizes (h1-h6, body, small)\n   - Line height recommendations\n   - Letter spacing recommendations\n2. Accessibility check (legibility, dyslexia-friendly options)\n3. Loading performance notes (font weights, display swap)\n4. Fallback font stacks\n5. Best use case for each pairing',
    category: 'design',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Beginner',
    tags: ['typography', 'fonts', 'design', 'branding'],
    author_name: 'TypeTactician',
    author_avatar: '🔤',
    featured: false,
    trending: false,
    copies_count: 3400,
    likes_count: 1100,
    rating_avg: 4.5,
    rating_count: 240,
    expected_output: 'Five font pairings with CSS, accessibility checks, and performance notes.',
    tips: 'Limit to 2-3 font weights per family for faster page loads.',
  },
  {
    slug: 'business-competitor-analysis',
    title: 'Competitor Analysis Deep Dive',
    description: 'Comprehensive competitor analysis with SWOT, positioning map, and differentiation strategy.',
    content: 'Perform a deep competitor analysis. My business: [DESCRIBE]. Competitors: [LIST 3-5]. Industry: [INDUSTRY]. Provide for each competitor:\n1. Company overview (founding, size, funding)\n2. Product/service comparison\n3. Pricing analysis\n4. Target market and positioning\n5. Marketing channels and strategy\n6. Strengths (3-5)\n7. Weaknesses (3-5)\n8. Notable features or innovations\n\nThen provide:\n9. Competitive positioning map (2x2 matrix description)\n10. Market gap analysis\n11. Differentiation opportunities for my business\n12. Threat assessment\n13. Strategic recommendations (prioritized)\n14. 90-day action plan to gain competitive advantage',
    category: 'business',
    ai_models: ['chatgpt', 'claude', 'gemini', 'perplexity'],
    difficulty: 'Advanced',
    tags: ['competitor-analysis', 'strategy', 'market-research', 'business'],
    author_name: 'CompetitorX',
    author_avatar: '🔬',
    featured: false,
    trending: false,
    copies_count: 3900,
    likes_count: 1300,
    rating_avg: 4.7,
    rating_count: 280,
    expected_output: 'A detailed competitor analysis with positioning map and differentiation strategy.',
    tips: 'Use Perplexity for real-time competitor data. ChatGPT\'s knowledge may be outdated.',
  },
  {
    slug: 'writing-content-repurposer',
    title: 'Content Repurposing Engine',
    description: 'Turn one piece of content into 10+ formats across all platforms with minimal effort.',
    content: 'Repurpose the following content for multiple platforms:\n\n[ORIGINAL CONTENT - blog post, video script, podcast, etc.]\n\nProvide repurposed versions for:\n1. Twitter/X thread (8-10 tweets)\n2. LinkedIn post (professional angle)\n3. Instagram carousel (10 slides with text)\n4. Instagram caption (with hashtags)\n5. TikTok/Reel script (30 seconds)\n6. YouTube Shorts script (60 seconds)\n7. Email newsletter section\n8. Podcast talking points\n9. Infographic content outline\n10. Medium article (expanded version)\n\nFor each: full text ready to post, with platform-specific formatting and hashtags.',
    category: 'writing',
    ai_models: ['chatgpt', 'claude', 'gemini'],
    difficulty: 'Intermediate',
    tags: ['content-repurposing', 'social-media', 'multi-platform', 'content'],
    author_name: 'ContentCyclone',
    author_avatar: '♻️',
    featured: false,
    trending: true,
    copies_count: 8100,
    likes_count: 2400,
    rating_avg: 4.7,
    rating_count: 560,
    expected_output: 'Ten platform-optimized versions of your original content, ready to post.',
    tips: 'Start with your best-performing content. Repurposing winners amplifies results.',
  },
];
