import {
  Sparkles, FileText, ListOrdered, Play, Image, Type, MessageSquare, Zap,
  Lightbulb, Hash, Search, Smartphone, ListMusic, User, Users, Vote, Clock,
  BookOpen, PenLine, Mail, Link2, LayoutTemplate, Megaphone, ShoppingCart,
  Globe, BarChart3, Palette, Briefcase, Share2, Target, Calculator,
  Calendar, Eye, TrendingUp, DollarSign, Award, ClipboardList, FileCode,
  HelpCircle, ShieldCheck, FileLock2, Cookie, Phone, MousePointerClick,
  Star, Quote, Layers, Repeat, AlertTriangle, Wrench, Camera,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type InputType = 'text' | 'textarea' | 'number' | 'multi-input';
export type OutputType = 'text' | 'list' | 'number';

export interface Tool {
  id: number;
  slug: string;
  name: string;
  description: string;
  category: string;
  icon: LucideIcon;
  featured: boolean;
  isNew: boolean;
  inputType: InputType;
  outputType: OutputType;
  linkHint?: string;
  scratchFields?: string[];
  linkRequired?: boolean;
  scratchOnly?: boolean;
  exampleInput?: string;
  exampleOutput?: string;
}

export interface Category {
  name: string;
  slug: string;
  icon: LucideIcon;
  glow: string;
}

export const CATEGORIES: Category[] = [
  { name: 'YouTube Tools', slug: 'youtube', icon: Play, glow: '#F2A93B' },
  { name: 'Instagram Tools', slug: 'instagram', icon: Camera, glow: '#F2A93B' },
  { name: 'TikTok Tools', slug: 'tiktok', icon: Smartphone, glow: '#F2A93B' },
  { name: 'LinkedIn Tools', slug: 'linkedin', icon: Users, glow: '#F2A93B' },
  { name: 'AI Writing', slug: 'ai-writing', icon: PenLine, glow: '#F2A93B' },
  { name: 'SEO Tools', slug: 'seo', icon: Search, glow: '#4C7EA8' },
  { name: 'Thumbnail Tools', slug: 'thumbnail', icon: Image, glow: '#F2A93B' },
  { name: 'Creator Utilities', slug: 'creator-utilities', icon: Wrench, glow: '#F2A93B' },
  { name: 'Marketing Tools', slug: 'marketing', icon: Megaphone, glow: '#4C7EA8' },
  { name: 'Social Media Tools', slug: 'social-media', icon: Share2, glow: '#F2A93B' },
  { name: 'Advertising Tools', slug: 'advertising', icon: Target, glow: '#F2A93B' },
  { name: 'Email Marketing', slug: 'email-marketing', icon: Mail, glow: '#F2A93B' },
  { name: 'Analytics Tools', slug: 'analytics', icon: BarChart3, glow: '#4C7EA8' },
  { name: 'Branding Tools', slug: 'branding', icon: Palette, glow: '#F2A93B' },
  { name: 'Business Tools', slug: 'business', icon: Briefcase, glow: '#F2A93B' },
  { name: 'Website Tools', slug: 'website', icon: Globe, glow: '#F2A93B' },
];

const YT = 'YouTube Tools';
const IG = 'Instagram Tools';
const TT = 'TikTok Tools';
const LI = 'LinkedIn Tools';
const AW = 'AI Writing';
const SEO = 'SEO Tools';
const TH = 'Thumbnail Tools';
const CU = 'Creator Utilities';
const MKT = 'Marketing Tools';
const SM = 'Social Media Tools';
const AD = 'Advertising Tools';
const EM = 'Email Marketing';
const AN = 'Analytics Tools';
const BR = 'Branding Tools';
const BIZ = 'Business Tools';
const WEB = 'Website Tools';

export const TOOLS: Tool[] = [
  // YouTube Tools (20)
  { id: 1, slug: 'youtube-title-generator', name: 'YouTube Title Generator', description: 'Generate compelling YouTube titles that boost CTR and search ranking', category: YT, icon: Sparkles, featured: true, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a YouTube video or channel URL...', scratchFields: ['niche', 'tone', 'goal'], exampleInput: 'How to build a PC from scratch for beginners', exampleOutput: '1. I Built a $500 Gaming PC (And You Can Too)\n2. Building a PC for the First Time - Complete Beginner Guide\n3. From Zero to Gaming PC: A Beginner\'s Build Guide\n4. Don\'t Buy a Prebuilt Until You Watch This PC Build' },
  { id: 2, slug: 'youtube-description-generator', name: 'YouTube Description Generator', description: 'Write SEO-optimized video descriptions with timestamps and links', category: YT, icon: FileText, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a YouTube video or channel URL...', scratchFields: ['niche', 'tone', 'keywords'] },
  { id: 3, slug: 'youtube-script-generator', name: 'YouTube Script Generator', description: 'Generate full video scripts with intro, body, and outro', category: YT, icon: FileText, featured: true, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a YouTube video or channel URL...', scratchFields: ['niche', 'length', 'style'] },
  { id: 4, slug: 'youtube-outline-generator', name: 'Video Outline Generator', description: 'Structure your video into clear sections before filming', category: YT, icon: ListOrdered, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a YouTube video or channel URL...', scratchFields: ['niche', 'length', 'format'] },
  { id: 5, slug: 'youtube-thumbnail-text', name: 'Thumbnail Text Generator', description: 'Generate punchy 2-4 word overlay text for thumbnails', category: YT, icon: Type, featured: true, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste your video URL or upload a thumbnail...', scratchFields: ['niche', 'emotion', 'word_limit'] },
  { id: 6, slug: 'youtube-thumbnail-headline', name: 'Thumbnail Headline Generator', description: 'Create curiosity-driven headlines designed for thumbnail overlays', category: YT, icon: Type, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a YouTube video or channel URL...', scratchFields: ['niche', 'tone', 'emotion'] },
  { id: 7, slug: 'youtube-intro-generator', name: 'Intro Generator', description: 'Write engaging video intros that hook viewers in the first 10 seconds', category: YT, icon: Zap, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a YouTube video or channel URL...', scratchFields: ['niche', 'tone', 'hook_style'] },
  { id: 8, slug: 'youtube-outro-generator', name: 'Outro Generator', description: 'Generate outro scripts with CTAs that drive subscriptions', category: YT, icon: MessageSquare, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a YouTube video or channel URL...', scratchFields: ['niche', 'tone', 'goal'] },
  { id: 9, slug: 'youtube-hook-generator', name: 'Hook Generator', description: 'Create scroll-stopping hooks for the first 3 seconds of your video', category: YT, icon: Zap, featured: true, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a YouTube video or channel URL...', scratchFields: ['niche', 'tone', 'hook_type'] },
  { id: 10, slug: 'youtube-idea-generator', name: 'Video Idea Generator', description: 'Get fresh video ideas based on your niche and audience', category: YT, icon: Lightbulb, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a YouTube video or channel URL...', scratchFields: ['niche', 'audience_level', 'content_pillar'] },
  { id: 11, slug: 'youtube-tag-generator', name: 'Tag Generator', description: 'Generate relevant tags to improve video discoverability', category: YT, icon: Hash, featured: false, isNew: false, inputType: 'textarea', outputType: 'list', linkHint: 'Paste a YouTube video or channel URL...', scratchFields: ['niche', 'primary_keyword'] },
  { id: 12, slug: 'youtube-keyword-generator', name: 'Keyword Generator', description: 'Find high-traffic keywords for your YouTube content strategy', category: YT, icon: Search, featured: false, isNew: false, inputType: 'textarea', outputType: 'list', linkHint: 'Paste a YouTube video or channel URL...', scratchFields: ['niche', 'search_intent'] },
  { id: 13, slug: 'youtube-shorts-idea', name: 'Shorts Idea Generator', description: 'Generate viral-worthy YouTube Shorts concepts from trends', category: YT, icon: Smartphone, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a YouTube video or channel URL...', scratchFields: ['niche', 'trend_type'] },
  { id: 14, slug: 'youtube-playlist-name', name: 'Playlist Name Generator', description: 'Create catchy, organized playlist titles for your channel', category: YT, icon: ListMusic, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a YouTube video or channel URL...', scratchFields: ['niche', 'tone', 'series_theme'] },
  { id: 15, slug: 'youtube-channel-name', name: 'Channel Name Generator', description: 'Find the perfect memorable name for your YouTube channel', category: YT, icon: User, featured: false, isNew: false, inputType: 'text', outputType: 'text', scratchOnly: true, scratchFields: ['niche', 'personality', 'keyword'] },
  { id: 16, slug: 'youtube-channel-description', name: 'Channel Description Generator', description: 'Write compelling channel about-section copy that converts visitors', category: YT, icon: FileText, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a YouTube video or channel URL...', scratchFields: ['niche', 'tone', 'value_prop'] },
  { id: 17, slug: 'youtube-community-post', name: 'Community Post Generator', description: 'Create engaging community tab posts that drive interaction', category: YT, icon: MessageSquare, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a YouTube video or channel URL...', scratchFields: ['niche', 'post_type', 'tone'] },
  { id: 18, slug: 'youtube-chapter-generator', name: 'Chapter Generator', description: 'Auto-generate timestamped chapters from your video transcript', category: YT, icon: Clock, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a YouTube video or channel URL...', linkRequired: true, scratchFields: ['niche', 'chapter_count', 'style'] },
  { id: 19, slug: 'youtube-summary-generator', name: 'Video Summary Generator', description: 'Summarize any video into a concise, readable format', category: YT, icon: BookOpen, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a YouTube video or channel URL...', linkRequired: true, scratchFields: ['niche', 'summary_length', 'use_case'] },
  { id: 20, slug: 'youtube-cta-generator', name: 'CTA Generator', description: 'Generate call-to-action lines that drive subscriptions and engagement', category: YT, icon: Megaphone, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a YouTube video or channel URL...', scratchFields: ['niche', 'goal', 'tone'] },

  // Instagram Tools (12)
  { id: 21, slug: 'instagram-caption-generator', name: 'Caption Generator', description: 'Write scroll-stopping Instagram captions that drive engagement', category: IG, icon: Sparkles, featured: true, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste an Instagram post, reel, or profile URL...', scratchFields: ['niche', 'tone', 'goal'] },
  { id: 22, slug: 'instagram-hashtag-generator', name: 'Hashtag Generator', description: 'Find the best hashtags to expand your Instagram reach', category: IG, icon: Hash, featured: false, isNew: false, inputType: 'textarea', outputType: 'list', linkHint: 'Paste an Instagram post, reel, or profile URL...', scratchFields: ['niche', 'topic_keyword'] },
  { id: 23, slug: 'instagram-bio-generator', name: 'Bio Generator', description: 'Craft a memorable Instagram bio that tells your story', category: IG, icon: User, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste an Instagram post, reel, or profile URL...', scratchFields: ['niche', 'personality', 'value_prop'] },
  { id: 24, slug: 'instagram-username-generator', name: 'Username Generator', description: 'Find a unique, available Instagram handle that fits your brand', category: IG, icon: User, featured: false, isNew: false, inputType: 'text', outputType: 'text', scratchOnly: true, scratchFields: ['niche', 'style', 'keyword'] },
  { id: 25, slug: 'instagram-reel-hook', name: 'Reel Hook Generator', description: 'Generate viral reel hooks that stop the scroll in 3 seconds', category: IG, icon: Zap, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste an Instagram post, reel, or profile URL...', scratchFields: ['niche', 'tone', 'hook_type'] },
  { id: 26, slug: 'instagram-carousel-generator', name: 'Carousel Generator', description: 'Plan multi-slide carousel posts that keep viewers swiping', category: IG, icon: Layers, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste an Instagram post, reel, or profile URL...', scratchFields: ['niche', 'slide_count', 'format'] },
  { id: 27, slug: 'instagram-story-idea', name: 'Story Idea Generator', description: 'Get fresh story ideas that boost views and engagement', category: IG, icon: Lightbulb, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste an Instagram post, reel, or profile URL...', scratchFields: ['niche', 'content_pillar'] },
  { id: 28, slug: 'instagram-comment-generator', name: 'Comment Generator', description: 'Write authentic comments that spark conversations', category: IG, icon: MessageSquare, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste an Instagram post, reel, or profile URL...', scratchFields: ['niche', 'tone'] },
  { id: 29, slug: 'instagram-dm-generator', name: 'DM Generator', description: 'Craft professional DMs for collabs, sales, and networking', category: IG, icon: Mail, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste an Instagram post, reel, or profile URL...', scratchFields: ['purpose', 'tone'] },
  { id: 30, slug: 'instagram-cta-generator', name: 'CTA Generator', description: 'Generate Instagram CTAs that drive clicks, saves, and shares', category: IG, icon: Megaphone, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste an Instagram post, reel, or profile URL...', scratchFields: ['niche', 'goal', 'tone'] },
  { id: 31, slug: 'instagram-giveaway-caption', name: 'Giveaway Caption Generator', description: 'Write giveaway captions that maximize entries and shares', category: IG, icon: Award, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste an Instagram post, reel, or profile URL...', scratchFields: ['niche', 'prize_type', 'entry_style'] },
  { id: 32, slug: 'instagram-pitch-generator', name: 'Influencer Pitch Generator', description: 'Write compelling pitch DMs to brands and creators', category: IG, icon: Mail, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste an Instagram post, reel, or profile URL...', scratchFields: ['niche', 'collab_type', 'tone'] },

  // TikTok Tools (7)
  { id: 33, slug: 'tiktok-hook-generator', name: 'Hook Generator', description: 'Create TikTok hooks that stop the scroll in the first second', category: TT, icon: Zap, featured: true, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a TikTok video or profile URL...', scratchFields: ['niche', 'tone', 'hook_type'] },
  { id: 34, slug: 'tiktok-caption-generator', name: 'Caption Generator', description: 'Write TikTok captions that boost engagement and discoverability', category: TT, icon: Sparkles, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a TikTok video or profile URL...', scratchFields: ['niche', 'tone'] },
  { id: 35, slug: 'tiktok-hashtag-generator', name: 'Hashtag Generator', description: 'Find trending TikTok hashtags for maximum reach', category: TT, icon: Hash, featured: false, isNew: false, inputType: 'textarea', outputType: 'list', linkHint: 'Paste a TikTok video or profile URL...', scratchFields: ['niche', 'topic_keyword'] },
  { id: 36, slug: 'tiktok-idea-generator', name: 'Video Idea Generator', description: 'Get viral TikTok video ideas tailored to your niche', category: TT, icon: Lightbulb, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a TikTok video or profile URL...', scratchFields: ['niche', 'trend_type'] },
  { id: 37, slug: 'tiktok-script-generator', name: 'Script Generator', description: 'Generate short-form TikTok scripts with hooks and pacing', category: TT, icon: FileText, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a TikTok video or profile URL...', scratchFields: ['niche', 'length', 'style'] },
  { id: 38, slug: 'tiktok-trending-planner', name: 'Trending Content Planner', description: 'Plan TikTok content around current trends and sounds', category: TT, icon: TrendingUp, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a TikTok video or profile URL...', scratchFields: ['niche', 'content_pillar', 'posting_frequency'] },
  { id: 39, slug: 'tiktok-sound-idea', name: 'Sound Idea Generator', description: 'Get sound and music suggestions that match your content mood', category: TT, icon: ListMusic, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a TikTok video or profile URL...', scratchFields: ['niche', 'mood'] },

  // LinkedIn Tools (7)
  { id: 40, slug: 'linkedin-post-generator', name: 'LinkedIn Post Generator', description: 'Write professional LinkedIn posts that drive engagement', category: LI, icon: PenLine, featured: true, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a LinkedIn post or profile URL...', scratchFields: ['niche', 'tone', 'goal'] },
  { id: 41, slug: 'linkedin-headline-generator', name: 'Headline Generator', description: 'Craft a LinkedIn headline that gets you found and remembered', category: LI, icon: Type, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a LinkedIn post or profile URL...', scratchFields: ['role', 'tone', 'achievement'] },
  { id: 42, slug: 'linkedin-about-generator', name: 'About Section Generator', description: 'Write a compelling LinkedIn about section that builds authority', category: LI, icon: FileText, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a LinkedIn post or profile URL...', scratchFields: ['role', 'tone', 'career_focus'] },
  { id: 43, slug: 'linkedin-connection-request', name: 'Connection Request Generator', description: 'Write connection requests that actually get accepted', category: LI, icon: Users, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a LinkedIn post or profile URL...', scratchFields: ['purpose', 'tone'] },
  { id: 44, slug: 'linkedin-cold-message', name: 'Cold Message Generator', description: 'Craft cold LinkedIn messages that get replies, not ignores', category: LI, icon: Mail, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a LinkedIn post or profile URL...', scratchFields: ['purpose', 'tone'] },
  { id: 45, slug: 'linkedin-comment-generator', name: 'Comment Generator', description: 'Write thoughtful LinkedIn comments that build your presence', category: LI, icon: MessageSquare, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a LinkedIn post or profile URL...', scratchFields: ['tone'] },
  { id: 46, slug: 'linkedin-poll-generator', name: 'Poll Generator', description: 'Create engaging LinkedIn polls that spark discussion', category: LI, icon: Vote, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a LinkedIn post or profile URL...', scratchFields: ['niche', 'poll_goal'] },

  // AI Writing (12)
  { id: 47, slug: 'blog-title-generator', name: 'Blog Title Generator', description: 'Generate click-worthy blog titles optimized for SEO and CTR', category: AW, icon: Sparkles, featured: true, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a blog post, article, or product page URL...', scratchFields: ['niche', 'tone', 'goal'] },
  { id: 48, slug: 'blog-outline-generator', name: 'Blog Outline Generator', description: 'Structure your blog post into clear, logical sections', category: AW, icon: ListOrdered, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a blog post, article, or product page URL...', scratchFields: ['niche', 'length', 'format'] },
  { id: 49, slug: 'article-generator', name: 'Article Generator', description: 'Generate full-length articles from a topic or outline', category: AW, icon: FileText, featured: true, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a blog post, article, or product page URL...', scratchFields: ['niche', 'tone', 'length'] },
  { id: 50, slug: 'email-generator', name: 'Email Generator', description: 'Write professional emails for any situation in seconds', category: AW, icon: Mail, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a blog post, article, or product page URL...', scratchFields: ['purpose', 'tone'] },
  { id: 51, slug: 'cold-email-generator', name: 'Cold Email Generator', description: 'Craft cold emails that get opened, read, and replied to', category: AW, icon: Mail, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a blog post, article, or product page URL...', scratchFields: ['purpose', 'tone'] },
  { id: 52, slug: 'sales-copy-generator', name: 'Sales Copy Generator', description: 'Write persuasive sales copy that converts visitors into customers', category: AW, icon: Megaphone, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a blog post, article, or product page URL...', scratchFields: ['niche', 'tone', 'goal'] },
  { id: 53, slug: 'landing-page-generator', name: 'Landing Page Generator', description: 'Generate complete landing page copy from headline to CTA', category: AW, icon: LayoutTemplate, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a blog post, article, or product page URL...', scratchFields: ['niche', 'tone', 'goal'] },
  { id: 54, slug: 'ad-copy-generator', name: 'Ad Copy Generator', description: 'Write high-converting ad copy for any platform', category: AW, icon: Megaphone, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a blog post, article, or product page URL...', scratchFields: ['niche', 'platform', 'goal'] },
  { id: 55, slug: 'product-description-generator', name: 'Product Description Generator', description: 'Write product descriptions that highlight benefits and drive sales', category: AW, icon: ShoppingCart, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a blog post, article, or product page URL...', scratchFields: ['niche', 'tone', 'features'] },
  { id: 56, slug: 'website-copy-generator', name: 'Website Copy Generator', description: 'Generate website copy for any page type and industry', category: AW, icon: Globe, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a blog post, article, or product page URL...', scratchFields: ['niche', 'tone', 'page_type'] },
  { id: 57, slug: 'press-release-generator', name: 'Press Release Generator', description: 'Write professional press releases that get picked up', category: AW, icon: FileText, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a blog post, article, or product page URL...', scratchFields: ['industry', 'tone', 'announcement_type'] },
  { id: 58, slug: 'proposal-generator', name: 'Business Proposal Generator', description: 'Generate detailed business proposals that win clients', category: AW, icon: Briefcase, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a blog post, article, or product page URL...', scratchFields: ['industry', 'tone', 'proposal_type'] },

  // SEO Tools (10)
  { id: 59, slug: 'meta-title-generator', name: 'Meta Title Generator', description: 'Generate SEO-optimized meta titles under 60 characters', category: SEO, icon: Type, featured: true, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste the page URL this is for...', scratchFields: ['page_topic', 'target_keyword'] },
  { id: 60, slug: 'meta-description-generator', name: 'Meta Description Generator', description: 'Write compelling meta descriptions that improve click-through', category: SEO, icon: FileText, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste the page URL this is for...', scratchFields: ['page_topic', 'target_keyword'] },
  { id: 61, slug: 'keyword-cluster-generator', name: 'Keyword Cluster Generator', description: 'Group keywords into topical clusters for content strategy', category: SEO, icon: Search, featured: false, isNew: false, inputType: 'textarea', outputType: 'list', linkHint: 'Paste the page URL this is for...', scratchFields: ['seed_keyword'] },
  { id: 62, slug: 'slug-generator', name: 'Slug Generator', description: 'Create clean, SEO-friendly URL slugs from any title', category: SEO, icon: Link2, featured: false, isNew: false, inputType: 'text', outputType: 'text', linkHint: 'Paste the page URL this is for...', scratchFields: ['page_title'] },
  { id: 63, slug: 'schema-generator', name: 'Schema Generator', description: 'Generate structured data markup for better search visibility', category: SEO, icon: FileCode, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste the page URL this is for...', scratchFields: ['page_type'] },
  { id: 64, slug: 'faq-generator', name: 'FAQ Generator', description: 'Generate FAQ sections with schema markup for rich snippets', category: SEO, icon: HelpCircle, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste the page URL this is for...', scratchFields: ['page_topic', 'question_count'] },
  { id: 65, slug: 'robots-txt-generator', name: 'Robots.txt Generator', description: 'Create a robots.txt file to control crawler access', category: SEO, icon: FileCode, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste the page URL this is for...', scratchFields: ['blocked_paths'] },
  { id: 66, slug: 'sitemap-generator', name: 'XML Sitemap Generator', description: 'Generate XML sitemaps for search engine submission', category: SEO, icon: FileCode, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste the page URL this is for...', scratchFields: ['page_url_list'] },
  { id: 67, slug: 'canonical-url-generator', name: 'Canonical URL Generator', description: 'Set canonical URLs to prevent duplicate content issues', category: SEO, icon: Link2, featured: false, isNew: false, inputType: 'text', outputType: 'text', linkHint: 'Paste the page URL this is for...', scratchFields: ['preferred_domain'] },
  { id: 68, slug: 'og-generator', name: 'Open Graph Generator', description: 'Generate Open Graph tags for social media sharing', category: SEO, icon: Share2, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste the page URL this is for...', scratchFields: ['page_title', 'description', 'image_url'] },

  // Thumbnail Tools (4)
  { id: 69, slug: 'thumbnail-text-generator', name: 'Thumbnail Text Generator', description: 'Generate punchy overlay text optimized for maximum CTR', category: TH, icon: Type, featured: true, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste your video URL or upload a thumbnail...', scratchFields: ['niche', 'emotion', 'word_limit'] },
  { id: 70, slug: 'thumbnail-headline', name: 'Thumbnail Headline Generator', description: 'Create curiosity-driven headlines for thumbnail overlays', category: TH, icon: Type, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste your video URL or upload a thumbnail...', scratchFields: ['niche', 'tone', 'emotion'] },
  { id: 71, slug: 'thumbnail-analyzer', name: 'Thumbnail Analyzer', description: 'Analyze your thumbnail for CTR optimization opportunities', category: TH, icon: Eye, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste your thumbnail image URL...', linkRequired: true },
  { id: 72, slug: 'ctr-suggestions', name: 'CTR Improvement Suggestions', description: 'Get actionable suggestions to improve your video CTR', category: TH, icon: TrendingUp, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste your video URL or upload a thumbnail...', scratchFields: ['niche', 'current_ctr', 'goal'] },

  // Creator Utilities (8)
  { id: 73, slug: 'content-calendar-generator', name: 'Content Calendar Generator', description: 'Generate a full content calendar tailored to your niche', category: CU, icon: Calendar, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste your channel/profile URL for context (optional)...', scratchFields: ['niche', 'posting_frequency', 'platforms'] },
  { id: 74, slug: 'posting-schedule-planner', name: 'Posting Schedule Planner', description: 'Plan optimal posting times across all your platforms', category: CU, icon: Clock, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste your channel/profile URL for context (optional)...', scratchFields: ['niche', 'timezone', 'platforms'] },
  { id: 75, slug: 'brand-color-generator', name: 'Brand Color Generator', description: 'Generate cohesive brand color palettes from a mood or niche', category: CU, icon: Palette, featured: false, isNew: false, inputType: 'text', outputType: 'text', scratchOnly: true, scratchFields: ['niche', 'mood'] },
  { id: 76, slug: 'font-pair-generator', name: 'Font Pair Generator', description: 'Find perfect font pairings for your brand or project', category: CU, icon: Type, featured: false, isNew: false, inputType: 'text', outputType: 'text', scratchOnly: true, scratchFields: ['style'] },
  { id: 77, slug: 'publishing-checklist', name: 'Video Publishing Checklist', description: 'Generate a pre-publish checklist for your content workflow', category: CU, icon: ClipboardList, featured: false, isNew: false, inputType: 'text', outputType: 'text', scratchOnly: true, scratchFields: ['platform', 'content_type'] },
  { id: 78, slug: 'idea-vault', name: 'Idea Vault', description: 'Generate and organize content ideas by pillar and niche', category: CU, icon: Lightbulb, featured: false, isNew: false, inputType: 'textarea', outputType: 'text', linkHint: 'Paste your channel/profile URL for context (optional)...', scratchFields: ['niche', 'content_pillars'] },
  { id: 79, slug: 'sponsorship-rate-calculator', name: 'Sponsorship Rate Calculator', description: 'Calculate fair sponsorship rates based on your metrics', category: CU, icon: DollarSign, featured: false, isNew: false, inputType: 'number', outputType: 'number' },
  { id: 80, slug: 'income-goal-calculator', name: 'Income Goal Calculator', description: 'Break down your income goals into actionable monthly targets', category: CU, icon: DollarSign, featured: false, isNew: false, inputType: 'number', outputType: 'number' },

  // Marketing Tools (existing: utm-builder + 8 calculators)
  { id: 81, slug: 'utm-builder', name: 'UTM Link Builder', description: 'Build UTM tracking links for any marketing campaign', category: MKT, icon: Link2, featured: false, isNew: false, inputType: 'multi-input', outputType: 'text' },
  { id: 82, slug: 'roi-calculator', name: 'ROI Calculator', description: 'Calculate return on investment for any campaign', category: MKT, icon: Calculator, featured: false, isNew: false, inputType: 'number', outputType: 'number' },
  { id: 83, slug: 'roas-calculator', name: 'ROAS Calculator', description: 'Measure return on ad spend across channels', category: MKT, icon: Calculator, featured: false, isNew: false, inputType: 'number', outputType: 'number' },
  { id: 84, slug: 'cpm-calculator', name: 'CPM Calculator', description: 'Calculate cost per thousand impressions', category: MKT, icon: Calculator, featured: false, isNew: false, inputType: 'number', outputType: 'number' },
  { id: 85, slug: 'cpc-calculator', name: 'CPC Calculator', description: 'Calculate cost per click for your ad campaigns', category: MKT, icon: Calculator, featured: false, isNew: false, inputType: 'number', outputType: 'number' },
  { id: 86, slug: 'cpa-calculator', name: 'CPA Calculator', description: 'Calculate cost per acquisition for your campaigns', category: MKT, icon: Calculator, featured: false, isNew: false, inputType: 'number', outputType: 'number' },
  { id: 87, slug: 'engagement-rate-calculator', name: 'Engagement Rate Calculator', description: 'Measure engagement rate across any platform', category: MKT, icon: Calculator, featured: false, isNew: false, inputType: 'number', outputType: 'number' },
  { id: 88, slug: 'conversion-rate-calculator', name: 'Conversion Rate Calculator', description: 'Calculate conversion rate for landing pages and funnels', category: MKT, icon: Calculator, featured: false, isNew: false, inputType: 'number', outputType: 'number' },
  { id: 89, slug: 'budget-calculator', name: 'Budget Allocator', description: 'Split your marketing budget across channels', category: MKT, icon: DollarSign, featured: false, isNew: false, inputType: 'number', outputType: 'number' },

  // Social Media Tools (10 new)
  { id: 90, slug: 'facebook-post-generator', name: 'Facebook Post Generator', description: 'Write engaging Facebook posts that spark conversation', category: SM, icon: Share2, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone', 'goal'] },
  { id: 91, slug: 'facebook-ad-copy-generator', name: 'Facebook Ad Copy Generator', description: 'Generate high-converting Facebook ad copy variations', category: SM, icon: Megaphone, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone', 'goal'] },
  { id: 92, slug: 'twitter-post-generator', name: 'X/Twitter Post Generator', description: 'Write punchy tweets that drive replies and retweets', category: SM, icon: Share2, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone'] },
  { id: 93, slug: 'twitter-thread-generator', name: 'Thread Generator', description: 'Create engaging X/Twitter threads from a single topic', category: SM, icon: ListOrdered, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone'] },
  { id: 94, slug: 'pinterest-pin-description', name: 'Pinterest Pin Description Generator', description: 'Write SEO-optimized Pinterest pin descriptions', category: SM, icon: Image, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone', 'keywords'] },
  { id: 95, slug: 'social-bio-generator', name: 'Universal Social Bio Generator', description: 'Create bios that work across all your social profiles', category: SM, icon: User, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'personality', 'value_prop'] },
  { id: 96, slug: 'social-post-idea-generator', name: 'Social Media Post Idea Generator', description: 'Get fresh post ideas for any platform and niche', category: SM, icon: Lightbulb, featured: false, isNew: true, inputType: 'text', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'platform'] },
  { id: 97, slug: 'hashtag-research-tool', name: 'Cross-Platform Hashtag Research Tool', description: 'Research hashtags that work across multiple platforms', category: SM, icon: Hash, featured: false, isNew: true, inputType: 'text', outputType: 'list', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'topic_keyword'] },
  { id: 98, slug: 'social-content-repurposer', name: 'Content Repurposing Generator', description: 'Turn one post into five platform-optimized formats', category: SM, icon: Repeat, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone'] },
  { id: 99, slug: 'social-crisis-response', name: 'Crisis Comment Response Generator', description: 'Craft professional responses to negative comments', category: SM, icon: AlertTriangle, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone'] },

  // Advertising Tools (10 new)
  { id: 100, slug: 'google-ads-headline-generator', name: 'Google Ads Headline Generator', description: 'Generate Google Ads headlines within character limits', category: AD, icon: Type, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone', 'goal'] },
  { id: 101, slug: 'google-ads-description-generator', name: 'Google Ads Description Generator', description: 'Write Google Ads descriptions that drive clicks', category: AD, icon: FileText, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone', 'goal'] },
  { id: 102, slug: 'display-ad-copy-generator', name: 'Display Ad Copy Generator', description: 'Create concise display ad copy for banner placements', category: AD, icon: Image, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone', 'goal'] },
  { id: 103, slug: 'retargeting-ad-generator', name: 'Retargeting Ad Copy Generator', description: 'Write retargeting ads that bring visitors back', category: AD, icon: Target, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone', 'goal'] },
  { id: 104, slug: 'ad-ab-variant-generator', name: 'Ad A/B Variant Generator', description: 'Generate multiple ad variants for A/B testing', category: AD, icon: Repeat, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone', 'goal'] },
  { id: 105, slug: 'usp-generator', name: 'Unique Selling Point Generator', description: 'Identify and articulate your unique selling propositions', category: AD, icon: Star, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone'] },
  { id: 106, slug: 'elevator-pitch-generator', name: 'Elevator Pitch Generator', description: 'Craft a compelling elevator pitch for any business', category: AD, icon: Megaphone, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone'] },
  { id: 107, slug: 'ad-headline-tester', name: 'Ad Headline Scorer', description: 'Score your ad headline and get improvement suggestions', category: AD, icon: BarChart3, featured: false, isNew: true, inputType: 'text', outputType: 'text' },
  { id: 108, slug: 'ad-budget-calculator', name: 'Ad Budget Allocator', description: 'Allocate your ad budget across channels and campaigns', category: AD, icon: DollarSign, featured: false, isNew: true, inputType: 'number', outputType: 'number' },
  { id: 109, slug: 'video-ad-script-generator', name: 'Video Ad Script Generator', description: 'Generate video ad scripts with hooks and CTAs', category: AD, icon: Play, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone', 'goal'] },

  // Email Marketing (10 new)
  { id: 110, slug: 'email-subject-line-generator', name: 'Email Subject Line Generator', description: 'Write subject lines that boost open rates', category: EM, icon: Mail, featured: true, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone', 'goal'] },
  { id: 111, slug: 'welcome-email-generator', name: 'Welcome Email Generator', description: 'Create welcome email sequences that nurture new subscribers', category: EM, icon: Mail, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone'] },
  { id: 112, slug: 'newsletter-generator', name: 'Newsletter Content Generator', description: 'Generate newsletter content that keeps subscribers engaged', category: EM, icon: FileText, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone'] },
  { id: 113, slug: 'abandoned-cart-email-generator', name: 'Abandoned Cart Email Generator', description: 'Recover lost sales with abandoned cart email sequences', category: EM, icon: ShoppingCart, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone'] },
  { id: 114, slug: 're-engagement-email-generator', name: 'Re-engagement Email Generator', description: 'Win back inactive subscribers with targeted emails', category: EM, icon: Mail, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone'] },
  { id: 115, slug: 'promotional-email-generator', name: 'Promotional Email Generator', description: 'Write promotional emails that drive clicks and conversions', category: EM, icon: Megaphone, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone', 'goal'] },
  { id: 116, slug: 'drip-sequence-generator', name: 'Drip Campaign Sequence Generator', description: 'Plan multi-email drip sequences that convert', category: EM, icon: Repeat, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone', 'goal'] },
  { id: 117, slug: 'email-signature-generator', name: 'Email Signature Generator', description: 'Create professional email signatures with your branding', category: EM, icon: FileText, featured: false, isNew: true, inputType: 'text', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone'] },
  { id: 118, slug: 'subject-line-ab-generator', name: 'Subject Line A/B Variant Generator', description: 'Generate subject line variants for A/B testing', category: EM, icon: Repeat, featured: false, isNew: true, inputType: 'text', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone'] },
  { id: 119, slug: 'email-preview-text-generator', name: 'Email Preview Text Generator', description: 'Write preheader text that complements your subject line', category: EM, icon: Mail, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', linkHint: 'Paste a relevant link...', scratchFields: ['niche', 'tone'] },

  // Analytics Tools (10 new — calculators)
  { id: 120, slug: 'bounce-rate-calculator', name: 'Bounce Rate Calculator', description: 'Calculate your website bounce rate from session data', category: AN, icon: Calculator, featured: false, isNew: true, inputType: 'number', outputType: 'number' },
  { id: 121, slug: 'clv-calculator', name: 'Customer Lifetime Value Calculator', description: 'Calculate the total value of a customer relationship', category: AN, icon: DollarSign, featured: false, isNew: true, inputType: 'number', outputType: 'number' },
  { id: 122, slug: 'churn-rate-calculator', name: 'Churn Rate Calculator', description: 'Measure customer churn rate to track retention', category: AN, icon: Calculator, featured: false, isNew: true, inputType: 'number', outputType: 'number' },
  { id: 123, slug: 'aov-calculator', name: 'Average Order Value Calculator', description: 'Calculate your average order value from sales data', category: AN, icon: ShoppingCart, featured: false, isNew: true, inputType: 'number', outputType: 'number' },
  { id: 124, slug: 'growth-rate-calculator', name: 'Growth Rate Calculator', description: 'Measure growth rate across any time period', category: AN, icon: TrendingUp, featured: false, isNew: true, inputType: 'number', outputType: 'number' },
  { id: 125, slug: 'nps-calculator', name: 'Net Promoter Score Calculator', description: 'Calculate your NPS from survey response data', category: AN, icon: Calculator, featured: false, isNew: true, inputType: 'number', outputType: 'number' },
  { id: 126, slug: 'cac-calculator', name: 'Customer Acquisition Cost Calculator', description: 'Calculate how much it costs to acquire each customer', category: AN, icon: DollarSign, featured: false, isNew: true, inputType: 'number', outputType: 'number' },
  { id: 127, slug: 'break-even-calculator', name: 'Break-Even Point Calculator', description: 'Find your break-even point in units and revenue', category: AN, icon: Calculator, featured: false, isNew: true, inputType: 'number', outputType: 'number' },
  { id: 128, slug: 'ab-significance-calculator', name: 'A/B Test Significance Calculator', description: 'Determine if your A/B test results are statistically significant', category: AN, icon: BarChart3, featured: false, isNew: true, inputType: 'number', outputType: 'number' },
  { id: 129, slug: 'ltv-cac-ratio-calculator', name: 'LTV:CAC Ratio Calculator', description: 'Calculate the ratio of lifetime value to acquisition cost', category: AN, icon: BarChart3, featured: false, isNew: true, inputType: 'number', outputType: 'number' },

  // Branding Tools (10 new)
  { id: 130, slug: 'brand-name-generator', name: 'Brand Name Generator', description: 'Generate memorable brand names from your niche and values', category: BR, icon: Sparkles, featured: true, isNew: true, inputType: 'text', outputType: 'text', scratchFields: ['niche', 'personality', 'keyword'] },
  { id: 131, slug: 'tagline-generator', name: 'Slogan/Tagline Generator', description: 'Create catchy slogans and taglines that stick', category: BR, icon: Type, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 132, slug: 'brand-voice-generator', name: 'Brand Voice Guide Generator', description: 'Define your brand voice with a complete style guide', category: BR, icon: BookOpen, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 133, slug: 'brand-story-generator', name: 'Brand Story Generator', description: 'Craft a compelling brand story that connects emotionally', category: BR, icon: BookOpen, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 134, slug: 'mission-statement-generator', name: 'Mission Statement Generator', description: 'Write mission statements that inspire and guide', category: BR, icon: FileText, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 135, slug: 'brand-values-generator', name: 'Brand Values Generator', description: 'Define core brand values that resonate with your audience', category: BR, icon: Star, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 136, slug: 'company-bio-generator', name: 'Company Bio Generator', description: 'Write professional company bios for any platform', category: BR, icon: FileText, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 137, slug: 'logo-concept-generator', name: 'Logo Concept Generator', description: 'Generate logo concept descriptions for your designer', category: BR, icon: Palette, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 138, slug: 'brand-archetype-quiz', name: 'Brand Archetype Finder', description: 'Discover your brand archetype and how to express it', category: BR, icon: Star, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 139, slug: 'rebranding-checklist', name: 'Rebranding Checklist Generator', description: 'Generate a comprehensive rebranding checklist for your project', category: BR, icon: ClipboardList, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },

  // Business Tools (10 new)
  { id: 140, slug: 'business-plan-outline', name: 'Business Plan Outline Generator', description: 'Generate a structured business plan outline', category: BIZ, icon: Briefcase, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['industry', 'tone'] },
  { id: 141, slug: 'swot-analysis-generator', name: 'SWOT Analysis Generator', description: 'Create a detailed SWOT analysis for any business', category: BIZ, icon: BarChart3, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['industry', 'tone'] },
  { id: 142, slug: 'business-name-generator', name: 'Business Name Generator', description: 'Find the perfect name for your business or startup', category: BIZ, icon: Sparkles, featured: false, isNew: true, inputType: 'text', outputType: 'text', scratchFields: ['industry', 'style', 'keyword'] },
  { id: 143, slug: 'pricing-strategy-generator', name: 'Pricing Strategy Generator', description: 'Develop pricing strategies tailored to your market', category: BIZ, icon: DollarSign, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['industry', 'tone'] },
  { id: 144, slug: 'competitor-analysis-generator', name: 'Competitor Analysis Generator', description: 'Analyze competitors and find your competitive edge', category: BIZ, icon: Search, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['industry', 'tone'] },
  { id: 145, slug: 'meeting-agenda-generator', name: 'Meeting Agenda Generator', description: 'Create structured meeting agendas that stay on track', category: BIZ, icon: ClipboardList, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['industry', 'tone'] },
  { id: 146, slug: 'job-description-generator', name: 'Job Description Generator', description: 'Write clear, compelling job descriptions that attract talent', category: BIZ, icon: FileText, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['industry', 'tone'] },
  { id: 147, slug: 'interview-questions-generator', name: 'Interview Questions Generator', description: 'Generate targeted interview questions for any role', category: BIZ, icon: HelpCircle, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['industry', 'tone'] },
  { id: 148, slug: 'customer-persona-generator', name: 'Customer Persona Generator', description: 'Create detailed customer personas for your marketing', category: BIZ, icon: Users, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['industry', 'tone'] },
  { id: 149, slug: 'okr-generator', name: 'OKR Generator', description: 'Generate objectives and key results aligned to your goals', category: BIZ, icon: Target, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['industry', 'tone'] },

  // Website Tools (10 new)
  { id: 150, slug: '404-page-generator', name: '404 Page Copy Generator', description: 'Write 404 page copy that keeps visitors on your site', category: WEB, icon: AlertTriangle, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 151, slug: 'privacy-policy-generator', name: 'Privacy Policy Generator', description: 'Generate a privacy policy tailored to your website', category: WEB, icon: ShieldCheck, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 152, slug: 'terms-of-service-generator', name: 'Terms of Service Generator', description: 'Create terms of service for your website or app', category: WEB, icon: FileLock2, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 153, slug: 'cookie-policy-generator', name: 'Cookie Policy Generator', description: 'Generate a cookie policy for GDPR compliance', category: WEB, icon: Cookie, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 154, slug: 'about-us-generator', name: 'About Us Page Generator', description: 'Write an about page that builds trust and connection', category: WEB, icon: Users, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 155, slug: 'contact-page-generator', name: 'Contact Page Copy Generator', description: 'Create contact page copy that encourages outreach', category: WEB, icon: Phone, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 156, slug: 'website-tagline-generator', name: 'Website Tagline Generator', description: 'Generate taglines that capture your site\'s value proposition', category: WEB, icon: Type, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 157, slug: 'cta-button-generator', name: 'CTA Button Text Generator', description: 'Generate high-converting CTA button text for any page', category: WEB, icon: MousePointerClick, featured: false, isNew: true, inputType: 'text', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 158, slug: 'testimonial-request-generator', name: 'Testimonial Request Email Generator', description: 'Write emails that get customers to leave testimonials', category: WEB, icon: Quote, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
  { id: 159, slug: 'pricing-page-copy-generator', name: 'Pricing Page Copy Generator', description: 'Write pricing page copy that drives conversions', category: WEB, icon: DollarSign, featured: false, isNew: true, inputType: 'textarea', outputType: 'text', scratchFields: ['niche', 'tone'] },
];
